
#include "internal.h"
#ifndef	V578CMD_DISABLE

#ifdef WIN32
#include "../dbugtools/paneldbg.h"
#include "../v568env/v5initenv.h"
#endif


TV5Context	gV5Context;


void V5_InitContext(void)
{
#ifdef	WIN32
	UINT8 idx = 0;
#endif
	memset(&gV5Context, 0, sizeof(TV5Context));
	V5_CtrlInitContext();
	V5_MarbInitContext();
	V5_VispInitContext();
	V5_DispInitContext();
	V5_JpegInitContext();

	V5_CtrlSetInfo((PTCtrlInfo)&gCtrlInfo);
#ifdef	WIN32
	idx = V5_GetCurPanel();
	V5_DispSetPanelInfo((PTPanelInfo)gW32PanelInfo[idx]);
#else
	V5_DispSetPanelInfo((PTPanelInfo)&gPanelInfo);
#endif
	V5_MarbSetInfo((PTMarbInfo)&gMarbInfo);
	V5_JpegSetInfo((PTJpegInfo)&gJpegInfo);
	V5_VispSetSensorInfo();

	//gV5Context.ctrl = V5_CtrlGetContext();
	//gV5Context.disp = V5_DispGetContext();
	//gV5Context.jpeg = V5_JpegGetContext();
	//gV5Context.marb = V5_MarbGetContext();
	//gV5Context.isp =  V5_VispGetContext();

	//gV5Context.photo = V5_PhotoGetContext();
	//gV5Context.camera = V5_CameraGetContext();
	gV5Context.mode = 0xff;
}

void V5_Open(void)
{
	V5_CtrlAllModReset();
	V5_InitContext();
	V5_CtrlOpen();
	V5_MarbOpen();
	V5_DispOpen();
	V5_VispOpen();
	V5_JpegOpen();	//order must be: ctrl, marb, disp, visp, jpeg

	V5_DispSetPanelState(PANEL_POWERON, 1);
	V5_VispSetSnrState(SENSOR_POWEROFF);
	V5_CameraOpen();
	V5_HJpegOpen();

#ifdef	WIN32
	PanelDbgInitContext();
#endif
}

static const UINT16 gModeSetting[][5] =
{
	{ MOD_CLK_JPEG_CORE | MOD_CLK_JPEG | MOD_CLK_LBUF, 
			PREVIEW_MODE, VISP_PREVIEW_MODE, DISP_ABL_MODE, JPEG_MODE_IDLE },
	{ 0, PREVIEWBRC_MODE, VISP_PREVIEWBRC_MODE, DISP_ABL_MODE, JPEG_MODE_CAPTURE },
	{ 0, PREVIEWFRAME_MODE, VISP_PREVIEWFRAME_MODE, DISP_ABL_MODE, JPEG_MODE_CAPTUREFRAME },
	{ 0, CAPTURESTILL_MODE, VISP_CAPTURE_MODE, DISP_ABL_MODE, JPEG_MODE_CAPTURE },
	{ 0, CAPTURESTILLTHUMB_MODE, VISP_CAPTURETHUMB_MODE, DISP_ABL_MODE, JPEG_MODE_CAPTURE },
	{ 0, CAPTUREVIDEO_MODE, VISP_CAPTURE_MODE, DISP_ABL_MODE, JPEG_MODE_CAPTURE },
	{ 0, CAPTUREVIDEOTHUMB_MODE, VISP_CAPTURETHUMB_MODE, DISP_ABL_MODE, JPEG_MODE_CAPTURE },
	{ 0, CAPTUREAVI_MODE, VISP_CAPTURE_MODE, DISP_ABL_MODE, JPEG_MODE_CAPTURE },
	{ 0, CAPTUREAVITHUMB_MODE, VISP_CAPTURETHUMB_MODE, DISP_ABL_MODE, JPEG_MODE_CAPTURE },
	{ 0, CAPTUREFRAME_MODE, VISP_CAPTUREFRAME_MODE, DISP_ABL_MODE, JPEG_MODE_CAPTUREFRAME },
	{ 0, CAPTUREFRAMEVIDEO_MODE, VISP_CAPTUREFRAME_MODE, DISP_ABL_MODE, JPEG_MODE_CAPTUREFRAME },
	{ 0, CAPTUREFRAMEAVI_MODE, VISP_CAPTUREFRAME_MODE, DISP_ABL_MODE, JPEG_MODE_CAPTUREFRAME },
	{ 0, MULTISHOT_MODE, VISP_CAPTURE_MODE, DISP_ABL_MODE, JPEG_MODE_CAPTURE },
	{ 0, MULTISHOTTHUMB_MODE, VISP_CAPTURETHUMB_MODE, DISP_ABL_MODE, JPEG_MODE_CAPTURE },
	{ MOD_CLK_SIF | MOD_CLK_ISP, DISPLAYSTILL_MODE, VISP_DISPLAY_MODE, DISP_ABL_MODE, JPEG_MODE_DISPLAY },
	{ MOD_CLK_SIF | MOD_CLK_ISP, ENCODE_MODE, VISP_ENCODE_DECODE_MODE, DISP_ABL_MODE, JPEG_MODE_ENCODE },
	{ MOD_CLK_SIF | MOD_CLK_ISP, DECODE_MODE, VISP_ENCODE_DECODE_MODE, DISP_ABL_MODE, JPEG_MODE_DECODE },
	{ MOD_CLK_SIF | MOD_CLK_ISP, DECODEIPP_MODE, VISP_DECODEIPP_MODE, DISP_ABL_MODE, JPEG_MODE_DECODEIPP },
	{ MOD_CLK_SIF | MOD_CLK_ISP, DECODEFRAME_MODE, VISP_DECODEFRAME_MODE, DISP_DEF_MODE, JPEG_MODE_DECODEFRAME },
	{ 0, MULTISHOTFRAME_MODE, VISP_CAPTUREFRAME_MODE, DISP_ABL_MODE, JPEG_MODE_CAPTUREFRAME },
	{ 0, CAPTURETHUMB_MODE, VISP_CAPTURETHUMB_MODE, DISP_ABL_MODE, CAPTURETHUMB_MODE },
	{ MOD_CLK_SIF | MOD_CLK_ISP, DISPLAYVIDEO_MODE, VISP_DISPLAY_MODE, DISP_ABL_MODE, JPEG_MODE_DISPLAY },
	{ MOD_CLK_SIF | MOD_CLK_ISP, DISPLAYAVI_MODE, VISP_DISPLAY_MODE, DISP_ABL_MODE, JPEG_MODE_DISPLAY },
	{ MOD_CLK_SIF | MOD_CLK_ISP | MOD_CLK_JPEG | MOD_CLK_JPEG_CORE | MOD_CLK_LBUF | MOD_CLK_IPP, 
			DIRECTDISPLAY_MODE, VISP_NOSTREAM_MODE, DISP_ABL_MODE, JPEG_MODE_IDLE },
	{ MOD_CLK_ALL, BYPASS_MODE, VISP_NOSTREAM_MODE, DISP_IDLE_MODE, JPEG_MODE_IDLE },//bypass
	{ MOD_CLK_SIF | MOD_CLK_ISP | MOD_CLK_JPEG | MOD_CLK_JPEG_CORE | MOD_CLK_LBUF | MOD_CLK_IPP | 
		MOD_CLK_LCDC | MOD_CLK_MARB_FAST | MOD_CLK_MARB | MOD_CLK_GE, 
		THROUGH_MODE, VISP_NOSTREAM_MODE, DISP_IDLE_MODE, JPEG_MODE_IDLE },
	{ MOD_CLK_SIF | MOD_CLK_ISP, DECODEIPPBYPASS_MODE, VISP_DECODEIPP_MODE, DISP_ABL_MODE, JPEG_MODE_DECODEIPP_BYPASS },
	{ MOD_CLK_SIF | MOD_CLK_ISP, DECODEFRAMEBYPASS_MODE, VISP_DECODEFRAME_MODE, DISP_DEF_MODE, JPEG_MODE_DECODEFRAME_BYPASS },
	{ MOD_CLK_SIF | MOD_CLK_ISP, DISPLAYBYPASS_MODE, VISP_DISPLAY_MODE, DISP_ABL_MODE, JPEG_MODE_DISPLAY_BYPASS },
	{ 0, CAPTUREFRAMETHUMB_MODE, VISP_CAPTURETHUMB_MODE, DISP_ABL_MODE, JPEG_MODE_CAPTUREFRAME },
	{ 0, CAPTUREFRAMEVIDEOTHUMB_MODE, VISP_CAPTURETHUMB_MODE, DISP_ABL_MODE, JPEG_MODE_CAPTUREFRAME },
	{ 0, CAPTUREFRAMEAVITHUMB_MODE, VISP_CAPTURETHUMB_MODE, DISP_ABL_MODE, JPEG_MODE_CAPTUREFRAME }
};


void V5_SetMode(UINT8 mode)
{
	if(mode > CAPTUREFRAMEAVITHUMB_MODE)
		mode = PREVIEW_MODE;

	if(gV5Context.mode == mode)
		return;

    if(gV5Context.mode == BYPASS_MODE)
		V5_CtrlBypassToNormal();

	V5B_CpmSetModClkVal(0);
	V5_MarbSetMode((UINT8)gModeSetting[mode][1]);
	V5_DispSetMode((UINT8)gModeSetting[mode][3]);
	V5_JpegSetMode((UINT8)gModeSetting[mode][4]);
	V5_VispSetMode((UINT8)gModeSetting[mode][2]);
	V5B_CpmSetModClkVal(gModeSetting[mode][0]);

#ifdef	WIN32
	PanelDbgSetMode(mode);
#endif

	if(mode == BYPASS_MODE)
	    V5_CtrlNormalToBypass();
    gV5Context.mode = mode;
}

UINT8 V5_GetMode(void)
{
	return gV5Context.mode;
}

void V5_Close(void)
{
	gV5Context.mode = 0xff;
}

#endif //V578CMD_DISABLE

