//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by v568Plane.rc
//
#define IDD_V558HOSTIF_DLG              130
#define IDD_V558DEMO_DLG                131
#define IDD_V568SIF_DLG                 132
#define IDD_V568ISP_DLG                 133
#define IDD_V568IPP_DLG                 134
#define IDD_V568LBUF_DLG                135
#define IDD_V568JPEG_DLG                136
#define IDD_V568MARB_DLG                137
#define IDD_V568LCDC_DLG                138
#define IDD_V568LCDIF_DLG               139
#define IDD_V568CPM_DLG                 140
#define IDD_V568USBC_DLG                141
#define IDD_V568AUDIOADC_DLG            142
#define IDD_V568SDIF_DLG                143
#define IDD_V568GE_DLG                  144
#define IDD_V568PHONE_DLG               145
#define IDD_V568HIGHAPI_DLG             146
#define IDD_V568TESTCHIP_DLG            147
#define IDD_V568BOARD_DLG               148
#define IDD_V568TEST1T_DLG              149
#define IDD_V568DEMO1_DLG               150
#define IDC_LAYERAOP_CHECK              1001
#define IDC_LEVELTRIGGER_CHECK          1001
#define IDC_LAYERADISP_CHECK            1002
#define IDC_LEVELTRIGGERLOW_CHECK       1002
#define IDC_EDGETRIGGERLOW_CHECK        1003
#define IDC_GPIOPINIDX_COMBO            1004
#define IDC_SRAMWRITE_CHECK             1005
#define IDC_NOPORT_CHECK                1006
#define IDC_BYPASSMODE_CHECK            1007
#define IDC_LCD16_CHECK                 1008
#define IDC_BTN_SETFLASH                1009
#define IDC_LINESTART_BUTTON            1009
#define IDC_BTN_JFIF_SPLIT              1009
#define IDC_BTN_SETDEFAULT              1009
#define IDC_BYSELTYPE_CHECK             1009
#define IDC_GPIOSELBYPASS_CHECK         1009
#define IDC_CHECK_CAP_PRE               1010
#define IDC_CHECK_FLASH_EN              1010
#define IDC_CHECK_AUTOSELBUSTYPE        1010
#define IDC_BTN_EXIF_SPLIT              1010
#define IDC_EDIT_ET                     1011
#define IDC_BUSTYPE_EDIT                1011
#define IDC_EDIT_FLASH_Y_THD            1012
#define IDC_EDIT_FLASH_ET               1013
#define IDC_BTN_GET_FLASH               1014
#define IDC_SX_SCROLLBAR                1015
#define IDC_SY_SCROLLBAR                1016
#define IDC_JPEGTYPE_COMBO              1017
#define IDC_BATCHWRITE_BUTTON           1017
#define IDC_EX_SCROLLBAR                1017
#define IDC_SX_EDIT                     1018
#define IDC_FRAMEDROP_COMBO             1019
#define IDC_REGTYPE_COMBO               1020
#define IDC_SY_EDIT                     1020
#define IDC_DECTYPE_COMBO               1020
#define IDC_REGADDR_EDIT                1021
#define IDC_EX_EDIT                     1021
#define IDC_REGVAL_EDIT                 1022
#define IDC_DATA_EDIT                   1022
#define IDC_REGADDR_SPIN                1023
#define IDC_INSTANT_CHECK               1024
#define IDC_BTN_VMALLOC                 1024
#define IDC_CSFLAG_EDIT                 1024
#define IDC_WRITEREG_BUTTON             1025
#define IDC_BTN_PRINTMEM                1025
#define IDC_CSMODE_COMBO                1025
#define IDC_REGREAD_BUTTON              1026
#define IDC_REGVAL_EDIT2                1027
#define IDC_CMDLIST_COMBO               1028
#define IDC_SENDCMD_BUTTON              1029
#define IDC_LENGTH_EDIT                 1030
#define IDC_ADDRESS_EDIT                1031
#define IDC_WRITESRAM_BUTTON            1032
#define IDC_READSRAM_BUTTON             1033
#define IDC_FILELENGTH_EDIT             1034
#define IDC_CMDPARA0_EDIT               1035
#define IDC_CMDPARA1_EDIT               1036
#define IDC_CMDPARA2_EDIT               1037
#define IDC_CMDPARA3_EDIT               1038
#define IDC_BUSMODE_EDIT                1039
#define IDC_DITHER_CHECK                1040
#define IDC_CMDPARA4_EDIT               1040
#define IDC_DITHEREN_CHECK              1040
#define IDC_CMDPARA5_EDIT               1041
#define IDC_CMDPARA6_EDIT               1042
#define IDC_TESTREGRW_BUTTON            1043
#define IDC_SENSOR_EDIT                 1044
#define IDC_DISPSTILL_BUTTON            1045
#define IDC_LCD_EDIT                    1045
#define IDC_CAPSTILL_BUTTON             1046
#define IDC_BTN_CAPTURE_SXGA            1046
#define IDC_BTN_CAPTURE_UNCHANGE        1047
#define IDC_CAPSTILL_ERROR_BUTTON       1047
#define IDC_EDIT_CAP_DELAY              1048
#define IDC_QT_TEST                     1048
#define IDC_BTN_PREVIEW_VGA             1049
#define IDC_QT_SET                      1049
#define IDC_WRITESB_BUTTON              1050
#define IDC_BUTTON_1                    1050
#define IDC_INITPANEL_BUTTON            1050
#define IDC_LCDCRST_BUTTON              1050
#define IDC_BUTTON_DEMO_IN              1050
#define IDC_BUTTON_EN_ISR               1050
#define IDC_BUTTON_TEST_IPP             1050
#define IDC_DRAWLINE_BUTTON             1050
#define IDC_BUTTON_CPM_INIT             1050
#define IDC_BUTTON_TESTSRAMTIME         1050
#define IDC_GETCONTENT_BUTTON           1050
#define IDC_BUTTON_TEST_SENSOR          1050
#define IDC_BUTTON_PROCESS              1050
#define IDC_BUTTON_SENSOR_WRITE         1051
#define IDC_READSB_BUTTON               1051
#define IDC_REFRESHMAP_BUTTON           1051
#define IDC_PREVIEWOPEN_BTN             1051
#define IDC_FRAMECOUNT_EDIT             1051
#define IDC_BUTTON_TEST_INT             1051
#define IDC_V5OPEN_BUTTON               1051
#define IDC_WRITEMB_BUTTON              1052
#define IDC_STARTWIDTH_EDIT             1052
#define IDC_WRITEPTN_BUTTON             1052
#define IDC_BUTTON_TEST_CLK             1052
#define IDC_PREVIEW_BUTTON              1052
#define IDC_JPEG                        1052
#define IDC_BUTTON_CLK_SET              1052
#define IDC_READMB_BUTTON               1053
#define IDC_BUTTON_4                    1053
#define IDC_IBUFSIZE_BUTTON             1053
#define IDC_DRAWIMAGE_BUTTON            1053
#define IDC_STARTHEIGHT_EDIT            1053
#define IDC_BITBLT_BUTTON               1053
#define IDC_BUTTON_TEST_CLOCK           1053
#define IDC_SETLAYERB0_BUTTON           1053
#define IDC_BUTTON_TEST                 1053
#define IDC_SET_B0_BUTTON               1053
#define IDC_REFRESH_BUTTON              1054
#define IDC_BUTTON_5                    1054
#define IDC_RAMSTART_BUTTON             1054
#define IDC_ENDWIDTH_EDIT               1054
#define IDC_BUTTON_TEST_RESET           1054
#define IDC_SETLAYERB1_BUTTON           1054
#define IDC_THUMB                       1054
#define IDC_1TTEST_EDIT                 1054
#define IDC_SDOPEN_BUTTON               1055
#define IDC_BUTTON_6                    1055
#define IDC_RAMEND_BUTTON               1055
#define IDC_PARSERJPG_BUTTON            1055
#define IDC_EDIT_IMAGE_WIDTH            1055
#define IDC_CLIP_BUTTON                 1055
#define IDC_BUTTON_RELEASE              1055
#define IDC_1TTEST_BUTTON               1055
#define IDC_SETLAYERB1_BUTTON2          1055
#define IDC_SET_B1_BUTTON               1055
#define IDC_CMDINDEX_BUTTON             1056
#define IDC_BUTTON_7                    1056
#define IDC_READPANEL_BUTTON            1056
#define IDC_JPGIMGWIDTH_EDIT            1056
#define IDC_EDIT_IMAGE_HEIGHT           1056
#define IDC_SETCOLOR_BUTTON             1056
#define IDC_B0DISPBMP_BUTTON            1056
#define IDC_1TTEST_STATIC               1056
#define IDC_BUTTON_CLK_SET2             1056
#define IDC_ACMDSEND_BUTTON2            1057
#define IDC_BUTTON_8                    1057
#define IDC_JPGIMGHEIGHT_EDIT           1057
#define IDC_STATIC_WIDTH                1057
#define IDC_B1DISPBMP_BUTTON            1057
#define IDC_STATIC_TIME                 1057
#define IDC_BUTTON_9                    1058
#define IDC_JPGWIDTH_EDIT               1058
#define IDC_STATIC_IMAGE_HEIGHT         1058
#define IDC_CAPSIZER_BUTTON             1058
#define IDC_BUTTON1                     1058
#define IDC_BUTTON_STAR                 1059
#define IDC_ENDHEIGHT_EDIT              1059
#define IDC_STATIC_WINDOW_WIDTH         1059
#define IDC_BUTTON_0                    1060
#define IDC_STEP_EDIT                   1060
#define IDC_STATIC_WINDOW_HEIGHT        1060
#define IDC_ALLREGTEST_CHECK            1060
#define IDC_BUTTON_CROSS                1061
#define IDC_JPGHEIGHT_EDIT              1061
#define IDC_STATIC_CAP_WIDTH            1061
#define IDC_DEMOFRAMECOUNT_EDIT         1061
#define IDC_BUTTON2                     1061
#define IDC_CAP_SHOT_BUTTON             1061
#define IDC_HSETCFG_BUTTON              1061
#define IDC_APPLY_BUTTON                1061
#define IDC_GAMMA_SET_BUTTON            1061
#define IDC_JUDGE_ENV_BUTTON            1061
#define IDC_BUTTON_ACCEPT               1062
#define IDC_JPGSOP_EDIT                 1062
#define IDC_STATIC_CAP_HEIGHT           1062
#define IDC_DEMOPARSERJPG_BUTTON        1062
#define IDC_BUTTON3                     1062
#define IDC_CAP_VIDEO_BUTTON            1062
#define IDC_SET_BLANK_BUTTON            1062
#define IDC_C_SIZER_BUTTON              1062
#define IDC_START_AE_BUTTON             1062
#define IDC_BUTTON_REJECT               1063
#define IDC_JPGDATAPOS_EDIT             1063
#define IDC_STATIC_DISP_WIDTH           1063
#define IDC_DEMOJPGIMGWIDTH_EDIT        1063
#define IDC_BUTTON4                     1063
#define IDC_BUTTON_UP                   1064
#define IDC_SPLITJPG_BUTTON             1064
#define IDC_STATIC_DISP_HEIGHT          1064
#define IDC_DEMOJPGIMGHEIGHT_EDIT       1064
#define IDC_CAP_PHOTO_BUTTON            1064
#define IDC_BUTTON_DOWN                 1065
#define IDC_DELAY_EDIT                  1065
#define IDC_EDIT_WIN_WIDTH              1065
#define IDC_DEMOJPGWIDTH_EDIT           1065
#define IDC_UP_BUTTON                   1065
#define IDC_BUTTON_LEFT                 1066
#define IDC_EDIT_WIN_HEIGHT             1066
#define IDC_DEMOJPGHEIGHT_EDIT          1066
#define IDC_TOTAL_TIME                  1066
#define IDC_DOWN_BUTTON                 1066
#define IDC_BUTTON_RIGHT                1067
#define IDC_EDIT_CAP_WIDTH              1067
#define IDC_DEMOJPGSOP_EDIT             1067
#define IDC_SPLITJPG_ALL_BUTTON         1067
#define IDC_BUTTON_MENU                 1068
#define IDC_EDIT_CAP_HEIGHT             1068
#define IDC_DEMOJPGDATAPOS_EDIT         1068
#define IDC_QF_SMP_TIME                 1068
#define IDC_BUTTON_15                   1069
#define IDC_EDIT_DISP_WIDTH             1069
#define IDC_CAPTURE_BUTTON              1069
#define IDC_QF                          1069
#define IDC_BUTTON_16                   1070
#define IDC_EDIT_DISP_HEIGHT            1070
#define IDC_DISPLAY_BUTTON              1070
#define IDC_QT_AUTO                     1070
#define IDC_DIGITALZOOM_RADIO           1070
#define IDC_DEMOBUTTON_UP               1071
#define IDC_EDIT_THUMB_WIDTH            1071
#define IDC_ENCODE_BUTTON               1071
#define IDC_FRAME_RATE_TEST             1071
#define IDC_DISPLAYVIDEO_BUTTON         1071
#define IDC_DEMOBUTTON_DOWN             1072
#define IDC_EDIT_THUMB_HEIGHT           1072
#define IDC_DECODE_BUTTON               1072
#define IDC_STATIC_FRAME_RATE           1072
#define IDC_DEMOBUTTON_LEFT             1073
#define IDC_STATIC_THUMB_WIDTH          1073
#define IDC_MULTISHOT1_BUTTON           1073
#define IDC_ADJUST_COMBO                1073
#define IDC_DEMO1CAPBUTTON              1073
#define IDC_MULTISHOT_BUTTON            1073
#define IDC_RUDE_THD_R1                 1073
#define IDC_DEMOBUTTON_RIGHT            1074
#define IDC_STATIC_THUMB_HEIGHT         1074
#define IDC_DISPSIZER_BUTTON            1074
#define IDC_DEMO1DECBUTTON              1074
#define IDC_RUDE_THD_R2                 1074
#define IDC_DEMOBUTTON_MENU             1075
#define IDC_EDIT_STARTX                 1075
#define IDC_DEMOSPLITJPG_BUTTON         1075
#define IDC_DEMO1DECBUTTON2             1075
#define IDC_DEMO1DISPLAYBUTTON          1075
#define IDC_RUDE_THD_L1                 1075
#define IDC_DISPPEARMENU_BTN            1076
#define IDC_EDIT_STARTY                 1076
#define IDC_OVERLAYKEYCOLOR_BUTTON      1076
#define IDC_DEMO1DISPLAYBUTTON2         1076
#define IDC_FIL_REFRESH                 1076
#define IDC_KCOLOR1_BUTTON              1076
#define IDC_RUDE_THD_L2                 1076
#define IDC_DEMOFRAMECOUNT_EDIT2        1076
#define IDC_VID_TIMER                   1076
#define IDC_CLEARDEMO_BTN               1077
#define IDC_EDIT_CAP_RATIO_INT          1077
#define IDC_BACKGROUND_BUTTON           1077
#define IDC_OVERLAYKEYCOLOR_BUTTON2     1077
#define IDC_KCOLOR0_BUTTON              1077
#define IDC_RUDE_SHF_R1                 1077
#define IDC_RECAP_CNT                   1077
#define IDC_EDIT_CAP_RATIO_DEC          1078
#define IDC_DIRDISP_START_EDIT          1078
#define IDC_BG_COLOR_BUTTON             1078
#define IDC_RUDE_SHF_R2                 1078
#define IDC_VID_STOP_CNT                1078
#define IDC_EDIT_DISP_RATIO_INT         1079
#define IDC_DIRDISP_SIZE_EDIT           1079
#define IDC_RUDE_SHF_L1                 1079
#define IDC_EDIT_DISP_RATIO_DEC         1080
#define IDC_CAPTURE_BUTTON2             1080
#define IDC_SIFCAPTURE_BUTTON           1080
#define IDC_RUDE_SHF_L2                 1080
#define IDC_RECAP_SIZE                  1080
#define IDC_EDIT_THUMB_RATIO            1081
#define IDC_RUDE_COMP0                  1081
#define IDC_VID_STOP_TIMECNT            1081
#define IDC_STATIC_STARTY               1082
#define IDC_RUDE_COMP1                  1082
#define IDC_RECAP_ACT_CNT               1082
#define IDC_STATIC_STARTX               1083
#define IDC_RUDE_COMP2                  1083
#define IDC_BUTTON_IPP_READ             1084
#define IDC_RUDE_COMP3                  1084
#define IDC_BUTTON_SETET                1085
#define IDC_BUTTON_3                    1085
#define IDC_UPDATE_BUTTON               1085
#define IDC_SET_BUTTON                  1085
#define IDC_BUTTON_ISP_APPLY            1085
#define IDC_DISP_BUTTON                 1085
#define IDC_BACKWRITE_BUTTON            1085
#define IDC_SETLAYERA_BUTTON            1085
#define IDC_PREFILTER_COMBO             1085
#define IDC_RUDE_COMP4                  1085
#define IDC_SNRWIDTH_EDIT               1086
#define IDC_PREFILTER_BUTTON            1086
#define IDC_SETLAYERA_BUTTON2           1086
#define IDC_SET_A_BUTTON                1086
#define IDC_RUDE_COMP5                  1086
#define IDC_SNRHEIGHT_EDIT              1087
#define IDC_DISPWIDTH_EDIT              1087
#define IDC_IMGWIDTH_EDIT               1087
#define IDC_RUDE_AC                     1087
#define IDC_SNRSIZE_COMBO               1088
#define IDC_DISPHEIGHT_EDIT             1088
#define IDC_IMGHEIGHT_EDIT              1088
#define IDC_RUDE_LEVEL                  1088
#define IDC_IPPSIZER_WIDTH_EDIT         1089
#define IDC_DISPHEIGHT_EDIT2            1089
#define IDC_SLEEPCNT_EDIT               1089
#define IDC_QF18                        1089
#define IDC_RUDE_THD_WC                 1089
#define IDC_IPPSIZER_HEIGHT_EDIT        1090
#define IDC_SLEEPCNT_EDIT2              1090
#define IDC_STEPCNT_EDIT                1090
#define IDC_RUDE_EN                     1090
#define IDC_AW_EDIT                     1091
#define IDC_RUDE_AC_EN                  1091
#define IDC_IPPSIZER_PX_EDIT            1092
#define IDC_ENH_EN                      1092
#define IDC_IPPSIZER_PY_EDIT            1093
#define IDC_DEC_BUTTON                  1093
#define IDC_IPPSIZER_PX_SCROLLBAR       1094
#define IDC_DISPWIDTH_EDIT2             1094
#define IDC_DSTWIDTH_EDIT               1094
#define IDC_DECIPP_BUTTON               1094
#define IDC_IPPSIZER_PY_SCROLLBAR       1095
#define IDC_DISPHEIGHT_EDIT3            1095
#define IDC_DSTHEIGHT_EDIT              1095
#define IDC_DISPSTILL_BUTTON4           1095
#define IDC_DECLCD_BUTTON               1095
#define IDC_IPPSIZER_WIDTH_SCROLLBAR    1096
#define IDC_DEC_BUTTON2                 1096
#define IDC_DEC_ALL_BUTTON              1096
#define IDC_IPPSIZER_HEIGHT_SCROLLBAR   1097
#define IDC_CAP_DLY_FEED                1097
#define IDC_IPPDISP_WIDTH_EDIT          1098
#define IDC_CAP_DLY_EN                  1098
#define IDC_IPPDISP_HEIGHT_EDIT         1099
#define IDC_IPPDISP_WIDTH_SCROLLBAR     1100
#define IDC_IPPDISP_HEIGHT_SCROLLBAR    1101
#define IDC_IPPCAP_WIDTH_EDIT           1102
#define IDC_IPPCAP_HEIGHT_EDIT          1103
#define IDC_IPPCAP_WIDTH_SCROLLBAR      1104
#define IDC_IPPCAP_HEIGHT_SCROLLBAR     1105
#define IDC_IPPTHUMB_WIDTH_EDIT         1106
#define IDC_THUMBEN_CHECK               1107
#define IDC_AH_EDIT                     1108
#define IDC_IPPTHUMB_HEIGHT_EDIT        1109
#define IDC_AX_EDIT                     1110
#define IDC_AY_EDIT                     1111
#define IDC_AX_SCROLLBAR                1112
#define IDC_AY_SCROLLBAR                1113
#define IDC_AW_SCROLLBAR                1114
#define IDC_AH_SCROLLBAR                1115
#define IDC_THUMB_WIDTH_SCROLLBAR       1116
#define IDC_AMW_EDIT                    1117
#define IDC_AMH_EDIT                    1118
#define IDC_ADX_EDIT                    1119
#define IDC_ADY_EDIT                    1120
#define IDC_ADXSCROLLBAR                1121
#define IDC_ADX_SCROLLBAR               1121
#define IDC_ADY_SCROLLBAR               1122
#define IDC_AMW_SCROLLBAR               1123
#define IDC_BW0_EDIT                    1124
#define IDC_BH0_EDIT                    1125
#define IDC_BX0_EDIT                    1126
#define IDC_BY0_EDIT                    1127
#define IDC_BX0_SCROLLBAR               1128
#define IDC_BY0_SCROLLBAR               1129
#define IDC_BW0_SCROLLBAR               1130
#define IDC_BH0_SCROLLBAR               1131
#define IDC_BRW_EDIT                    1132
#define IDC_BRW0_EDIT                   1132
#define IDC_BRH_EDIT                    1133
#define IDC_BRH0_EDIT                   1133
#define IDC_BRX_EDIT                    1134
#define IDC_BRX0_EDIT                   1134
#define IDC_BRY_EDIT                    1135
#define IDC_BRY0_EDIT                   1135
#define IDC_BRX_SCROLLBAR               1136
#define IDC_BRX0_SCROLLBAR              1136
#define IDC_BRY_SCROLLBAR               1137
#define IDC_BRY0_SCROLLBAR              1137
#define IDC_BRW_SCROLLBAR               1138
#define IDC_BRW0_SCROLLBAR              1138
#define IDC_BRH_SCROLLBAR               1139
#define IDC_BRH0_SCROLLBAR              1139
#define IDC_AMHEIGHT_SCROLLBAR          1140
#define IDC_AMH_SCROLLBAR               1140
#define IDC_BMW0_EDIT                   1141
#define IDC_BMH0_EDIT                   1142
#define IDC_BDX0_EDIT                   1143
#define IDC_BDY0_PY_EDIT                1144
#define IDC_BDY0_EDIT                   1144
#define IDC_BDX0_SCROLLBAR              1145
#define IDC_BDY0_SCROLLBAR              1146
#define IDC_BMW0_SCROLLBAR              1147
#define IDC_LBMH0_SCROLLBAR             1148
#define IDC_BMH0_SCROLLBAR              1148
#define IDC_PANELWIDTH_EDIT             1149
#define IDC_PANELHEIGHT_EDIT            1150
#define IDC_OVERMODE_COMBO              1151
#define IDC_B1OVERLAYMODE_COMBO         1151
#define IDC_THUMB_HEIGHT_SCROLLBAR      1152
#define IDC_OVERMODE_COMBO2             1152
#define IDC_B0OVERLAYMODE_COMBO         1152
#define IDC_BLEND_EDIT                  1153
#define IDC_BLEND0_EDIT                 1153
#define IDC_BLEND_SCROLLBAR             1154
#define IDC_BLEND0_SCROLLBAR            1154
#define IDC_PREFILTEREN_CHECK           1155
#define IDC_BLENDEN_CHECK               1156
#define IDC_OVERLAYEN_CHECK             1157
#define IDC_AROTMODE_COMBO              1158
#define IDC_AROTATION_COMBO             1158
#define IDC_GAMMAEN_CHECK               1159
#define IDC_BROTMODE_COMBO              1160
#define IDC_BROTATION_COMBO             1160
#define IDC_B0FMT_COMBO                 1161
#define IDC_LBFMT_COMBO                 1161
#define IDC_B1FMT_COMBO                 1162
#define IDC_BRIGHTNESS_EDIT             1163
#define IDC_BRIGHTNESS_SCROLLBAR        1164
#define IDC_CONTRAST_EDIT               1165
#define IDC_CONTRAST_SCROLLBAR          1166
#define IDC_SATURATION_EDIT             1167
#define IDC_SATURATION_SCROLLBAR        1168
#define IDC_HUE_EDIT                    1169
#define IDC_HUE_SCROLLBAR               1170
#define IDC_B1SELECT_CHECK              1171
#define IDC_B1ENABLE_CHECK              1171
#define IDC_BFIRSTEN_CHECK              1172
#define IDC_B0FIRST_CHECK               1172
#define IDC_COMBO1                      1173
#define IDC_COMBO_FILT_FUNC             1173
#define IDC_JCOMPRESS_COMBO             1173
#define IDC_INPUT_COMBO                 1173
#define IDC_BRW_EDIT2                   1173
#define IDC_BRW1_EDIT                   1173
#define IDC_SPE_TYPE_COMBO              1173
#define IDC_POLARITY_MODE_COMBO         1173
#define IDC_GAMMA_SEL_COMBO             1173
#define IDC_BAR_AEWIN_WIDTH             1174
#define IDC_WSC_SCROLLBAR               1174
#define IDC_BGX_SCROLLBAR               1174
#define IDC_SCR_HA                      1174
#define IDC_SCRBAR_IMAGE_WIDTH          1174
#define IDC_FONTSX_SCROLLBAR            1174
#define IDC_DITHERSELECT_COMBO          1174
#define IDC_FRAME_CHECK                 1174
#define IDC_STATIC_SRC                  1174
#define IDC_BUTTON_FLASH_CHARGE         1175
#define IDC_BUTTON_2                    1175
#define IDC_BUTTON_DEMO_RETVIEW         1175
#define IDC_BUTTON_DIS_ISR              1175
#define IDC_BTN_LOADFONT                1175
#define IDC_GPIOCONFIGSET_BUTTON        1175
#define IDC_thumbnail_CHECK             1175
#define IDC_THUMBNAIL_CHECK             1175
#define IDC_STATIC_DST                  1175
#define IDC_FRAME_CHECK2                1175
#define IDC_BRH_EDIT2                   1175
#define IDC_DITHERSELECT_COMBO2         1175
#define IDC_DITHERSEL_COMBO             1175
#define IDC_BUTTON_APPLY                1176
#define IDC_BUTTON_DEMO_CAP_STILL       1176
#define IDC_SCR_HB                      1176
#define IDC_DSTBLSEL_COMBO              1176
#define IDC_GPIOMODESET_BUTTON          1176
#define IDC_EDIT_SRAM_ADDR              1176
#define IDC_LIST1                       1176
#define IDC_LCDCWSC_SCROLLBAR           1176
#define IDC_BUTTON_STOP_FLASH_CHARGE    1177
#define IDC_BUTTON_DEMO_DISP_STILL      1177
#define IDC_SCR_HC                      1177
#define IDC_DSTSPAN_EDIT                1177
#define IDC_GPIODIRSET_BUTTON           1177
#define IDC_EDIT_SRAM_SIZE              1177
#define IDC_EDIT_TWC                    1177
#define IDC_COMBO2                      1177
#define IDC_AWB_COMBO                   1177
#define IDC_LCDCWRC_SCROLLBAR           1177
#define IDC_BRX_EDIT2                   1177
#define IDC_WORK_MODE_COMBO             1177
#define IDC_BUTTON_START_FLASH          1178
#define _BUTTON_DEMO_ENC                1178
#define IDC_SCR_HD                      1178
#define IDC_GELINE_SPX_SCROLLBAR        1178
#define IDC_GPIOWRITEVALUE_BUTTON       1178
#define IDC_EDIT_SRAM_TOTAL_TIME        1178
#define IDC_COMBO3                      1178
#define IDC_SCENCE_COMBO                1178
#define IDC_LCDCDHC_SCROLLBAR           1178
#define IDC_BRY_EDIT2                   1178
#define IDC_DATA_SRC_COMBO              1178
#define IDC_BUTTON_STOP_FLASH           1179
#define IDC_BUTTON_DEMO_MUL_RETVIEW     1179
#define IDC_SCR_HE                      1179
#define IDC_GELINE_SPY_SCROLLBAR        1179
#define IDC_GPIOREADVALUE_BUTTON        1179
#define IDC_EDIT_BYTE_TIME              1179
#define IDC_COMBO4                      1179
#define IDC_AE_COMBO                    1179
#define IDC_TEST_BUTTON                 1179
#define IDC_BRX_SCROLLBAR2              1179
#define IDC_TMB_SRC_COMBO               1179
#define IDC_BUTTON_DEMO_CAP_VIDEO       1180
#define IDC_SCR_VA                      1180
#define IDC_GELINE_SPX_EDIT             1180
#define IDC_EDIT_DELAY_ADDR             1180
#define IDC_COMBO5                      1180
#define IDC_FLASH_COMBO                 1180
#define IDC_LCDCFR_STATIC               1180
#define IDC_BRY_SCROLLBAR2              1180
#define IDC_SENSOR_DATA_COMBO           1180
#define IDC_HIST_SEL_COMBO              1180
#define IDC_BUTTON_DEMO_CAP_FRAME       1181
#define IDC_SCR_VB                      1181
#define IDC_GELINE_SPY_EDIT             1181
#define IDC_EDIT_INIT_REGADDR           1181
#define IDC_COMBO6                      1181
#define IDC_SPECIALEFFECT_COMBO         1181
#define IDC_LCDCLO_STATIC               1181
#define IDC_SYNC_MODE_COMBO             1181
#define IDC_THUMB_FMT_COMBO             1181
#define IDC_BUTTON_DEMO_DISP_VIDEO      1182
#define IDC_SCR_VC                      1182
#define IDC_GELINE_EPX_EDIT             1182
#define IDC_EDIT_SRAM_TOTAL_TIME2       1182
#define IDC_HOSTIFBUSSPEED_EDIT         1182
#define IDC_COMBO7                      1182
#define IDC_ROTATION_COMBO              1182
#define IDC_BW1_EDIT2                   1182
#define IDC_BW1_EDIT                    1182
#define IDC_SYNC_DIR_COMBO              1182
#define IDC_BUTTON_DEMO_DISP_FRAME      1183
#define IDC_SCR_VD                      1183
#define IDC_GELINE_EPY_EDIT             1183
#define IDC_EDIT1                       1183
#define IDC_MSHOTCOUNT_EDIT             1183
#define IDC_BH1_EDIT2                   1183
#define IDC_BH1_EDIT                    1183
#define IDC_UOFFSET_EDIT                1183
#define IDC_IPP_WINX_EDIT               1183
#define IDC_SNR_CLK_EDIT                1183
#define IDC_HSTARTA_EDIT                1183
#define IDC_CMD_SX_EDIT                 1183
#define IDC_EDIT_SEC_ST                 1183
#define _BUTTON_DEMO_DEC                1184
#define IDC_SCR_VE                      1184
#define IDC_GELINE_EPX_SCROLLBAR        1184
#define IDC_EDIT2                       1184
#define IDC_JFILESIZE_EDIT              1184
#define IDC_JCOMPRESS_EDIT              1184
#define IDC_LCDCWSC_EDIT                1184
#define IDC_VOFFSET_EDIT                1184
#define IDC_IPP_WINY_EDIT               1184
#define IDC_PIXEL_RATE_EDIT             1184
#define IDC_HSTARTB_EDIT                1184
#define IDC_CMD_EX_EDIT                 1184
#define IDC_EDIT_SEC_ED                 1184
#define IDC_BUTTON_DEMO_CAP_MUL         1185
#define IDC_GELINE_EPY_SCROLLBAR        1185
#define IDC_RADIO1                      1185
#define IDC_JCOMPCONFIRM_BUTTON         1185
#define IDC_BX1_EDIT2                   1185
#define IDC_BX1_EDIT                    1185
#define IDC_RADIO_DEC_NORM              1185
#define IDC_RADIO_COM                   1185
#define IDC_LINECOLOR_EDIT              1186
#define IDC_RADIO2                      1186
#define IDC_FRAME_COMBO                 1186
#define IDC_DISPLAYSTILL_BUTTON         1186
#define IDC_BY1_EDIT2                   1186
#define IDC_BY1_EDIT                    1186
#define IDC_RADIO_DEC_AUTO              1186
#define IDC_EDIT_TCR2                   1186
#define IDC_EDIT_TCR                    1186
#define IDC_RADIO_USB                   1186
#define IDC_SRC_SPX_EDIT                1187
#define IDC_EDIT_DELAY_OE               1187
#define IDC_EDIT3                       1187
#define IDC_JCOMPRATIO_EDIT             1187
#define IDC_Frame_COMBO                 1187
#define IDC_FRAMEITEM_COMBO             1187
#define IDC_LCDCWRC_EDIT                1187
#define IDC_MGAIN_EDIT                  1187
#define IDC_UTOP_EDIT                   1187
#define IDC_IPP_WINW_EDIT               1187
#define IDC_SI_CLK_EDIT                 1187
#define IDC_HSTARTC_EDIT                1187
#define IDC_CMD_SY_EDIT                 1187
#define IDC_EDIT_TEST_CNT               1187
#define IDC_SRC_SPY_EDIT                1188
#define IDC_EDIT_DELAY_DATAIN           1188
#define IDC_LBH1_SCROLLBAR              1188
#define IDC_EDIT4                       1188
#define IDC_MSHOTINTERVAL_EDIT          1188
#define IDC_LCDCDHC_EDIT                1188
#define IDC_AVAL_EDIT                   1188
#define IDC_UBTM_EDIT                   1188
#define IDC_IPP_WINH_EDIT               1188
#define IDC_I2C_CLK_EDIT                1188
#define IDC_HSTARTD_EDIT                1188
#define IDC_CMD_EY_EDIT                 1188
#define IDC_EDIT_RD_SPEED               1188
#define IDC_SRC_SPX_SCROLLBAR           1189
#define IDC_EDIT_DELAY_DATAOUT          1189
#define IDC_CAPSIZE_COMBO               1189
#define IDC_BX1_SCROLLBAR2              1189
#define IDC_BX1_SCROLLBAR               1189
#define IDC_RADIO_DEC_FEED              1189
#define IDC_RADIO_VID_STOP_CNT          1189
#define IDC_EDIT_WR_SPEED               1189
#define IDC_SRC_SPY_SCROLLBAR           1190
#define IDC_EDIT_END_REGADDR            1190
#define IDC_HAPIREFRESH_BUTTON          1190
#define IDC_BY1_SCROLLBAR2              1190
#define IDC_BY1_SCROLLBAR               1190
#define IDC_RADIO_VID_STOP_TIME         1190
#define IDC_EDIT_WR_SPEED2              1190
#define IDC_PTNSRCBGCOLOR_EDIT          1191
#define IDC_EDIT5                       1191
#define IDC_VIDEOLENGTH_EDIT            1191
#define IDC_BW1_SCROLLBAR2              1191
#define IDC_BW1_SCROLLBAR               1191
#define IDC_VTOP_EDIT                   1191
#define IDC_IPP_DSW_EDIT                1191
#define IDC_I2C_INTERVAL_EDIT           1191
#define IDC_BARW_EDIT                   1191
#define IDC_RPT_SX_EDIT                 1191
#define IDC_B0START_EDIT                1192
#define IDC_PTNSRCFGCOLOR_EDIT          1192
#define IDC_WITHTHUMB_CHECK             1192
#define IDC_LBH1_SCROLLBAR2             1192
#define IDC_BH1_SCROLLBAR               1192
#define IDC_RADIO_VID_STOP_HOST         1192
#define IDC_B0END_EDIT                  1193
#define IDC_CHECK_PREFILTER_EN          1193
#define IDC_SRCEXPBGCOLOR_EDIT          1193
#define IDC_BYPASSDRAWBITMAP_BUTTON     1193
#define IDC_AF_CHECK                    1193
#define IDC_BMW1_EDIT2                  1193
#define IDC_BMW1_EDIT                   1193
#define IDC_WORKMODE_COMBO              1194
#define IDC_COMBO_SPECIAL_EFFECT        1194
#define IDC_SRCEXPFGCOLOR_EDIT          1194
#define IDC_BYPASSDRAWLINE_BUTTON       1194
#define IDC_SPECIALEFFECT_COMBO2        1194
#define IDC_BMH1_EDIT2                  1194
#define IDC_BMH1_EDIT                   1194
#define IDC_B1START_EDIT                1195
#define IDC_CLIP_SPX_EDIT               1195
#define IDC_SIZER_SCROLLBAR             1195
#define IDC_BDX1_EDIT2                  1195
#define IDC_BDX1_EDIT                   1195
#define IDC_B1END_EDIT                  1196
#define IDC_SRCBSEL_COMBO               1196
#define IDC_BYPASSINIT_BUTTON           1196
#define IDC_PPPCONFIRM_BUTTON           1196
#define IDC_BDY1_EDIT2                  1196
#define IDC_BDY1_EDIT                   1196
#define IDC_LBUF0START_EDIT             1197
#define IDC_DST_SPX_EDIT                1197
#define IDC_DEMOWORKMODE_COMBO          1197
#define IDC_BYPASSCSCHANGE_BUTTON       1197
#define IDC_BDX1_SCROLLBAR2             1197
#define IDC_BMW1_SCROLLBAR              1197
#define IDC_LBUF0END_EDIT               1198
#define IDC_DST_SPY_EDIT                1198
#define IDC_DEMOCAPYUVMODE_COMBO        1198
#define IDC_DECODEIPPSAVE_BUTTON        1198
#define IDC_BDY1_SCROLLBAR2             1198
#define IDC_BDX1_SCROLLBAR              1198
#define IDC_LBUF1START_EDIT             1199
#define IDC_DST_SPX_SCROLLBAR           1199
#define IDC_COMBO8                      1199
#define IDC_JCOMPRESS_COMBO2            1199
#define IDC_BRW_SCROLLBAR2              1199
#define IDC_BMW1_SCROLLBAR2             1199
#define IDC_BDY1_SCROLLBAR              1199
#define IDC_BUS_SEL_COMBO               1199
#define IDC_PIXEL_RATE_COMBO            1199
#define IDC_LBUF1END_EDIT               1200
#define IDC_DST_SPY_SCROLLBAR           1200
#define IDC_STATEN_CHECK                1200
#define IDC_BRH_SCROLLBAR2              1200
#define IDC_BMH1_SCROLLBAR2             1200
#define IDC_LBH1_SCROLLBAR6             1200
#define IDC_BMH1_SCROLLBAR              1200
#define IDC_THUMBSTART_EDIT             1201
#define IDC_CLIP_SPY_EDIT               1201
#define IDC_BALEN_CHECK                 1201
#define IDC_BFIRSTEN_CHECK2             1201
#define IDC_BRH_EDIT3                   1201
#define IDC_BRH1_EDIT                   1201
#define IDC_THUMBEND_EDIT               1202
#define IDC_DST_WIDTH_EDIT              1202
#define IDC_ENCIMAGEWIDTH_EDIT          1202
#define IDC_ARMDEMO_CHECK               1202
#define IDC_MGAINEN_CHECK               1202
#define IDC_BRX_EDIT3                   1202
#define IDC_BRX1_EDIT                   1202
#define IDC_INDEXSTART_EDIT             1203
#define IDC_DST_HEIGHT_EDIT             1203
#define IDC_ENCIMAGEHEIGHT_EDIT         1203
#define IDC_SAVESTAT_BUTTON             1203
#define IDC_BRY_EDIT3                   1203
#define IDC_BRY1_EDIT                   1203
#define IDC_INDEXEND_EDIT               1204
#define IDC_DST_WIDTH_SCROLLBAR         1204
#define IDC_ENCJPEGFORMAT_COMBO         1204
#define IDC_SCROLLBAR1                  1204
#define IDC_AVAL_SCROLLBAR              1204
#define IDC_BRX_SCROLLBAR3              1204
#define IDC_BRX1_SCROLLBAR              1204
#define IDC_UOFFSET_SCROLLBAR           1204
#define IDC_JBUFSTART_EDIT              1205
#define IDC_DST_HEIGHT_SCROLLBAR        1205
#define IDC_KEYCOLOR_EDIT               1205
#define IDC_KCOLOR1_EDIT                1205
#define IDC_JBUFEND_EDIT                1206
#define IDC_CLIP_SPX_SCROLLBAR          1206
#define IDC_LIST_INT_TYPE               1206
#define IDC_BLEND_EDIT2                 1206
#define IDC_KEYCOLOR_EDIT2              1206
#define IDC_KCOLOR0_EDIT                1206
#define IDC_A0START_EDIT                1207
#define IDC_BITWISE_EDIT                1207
#define IDC_CHECK_INTALL                1207
#define IDC_BLEND_SCROLLBAR2            1207
#define IDC_BRY_SCROLLBAR3              1207
#define IDC_BRY1_SCROLLBAR              1207
#define IDC_A0END_EDIT                  1208
#define IDC_MONOSRC_CHECK               1208
#define IDC_STATIC_BLE2                 1208
#define IDC_A1STARTEDIT                 1209
#define IDC_MONOPTN_CHECK               1209
#define IDC_OVLYMODE_COMBO              1209
#define IDC_BRW_SCROLLBAR3              1209
#define IDC_BRW1_SCROLLBAR              1209
#define IDC_A1END_EDIT                  1210
#define IDC_SRCWRMASK_CHECK             1210
#define IDC_DATETIMEPICKER1             1210
#define IDC_BRH_SCROLLBAR3              1210
#define IDC_BRH1_SCROLLBAR              1210
#define IDC_ALLOCMODE_COMBO             1211
#define IDC_TRANSPARENT_CHECK           1211
#define IDC_BLEND_EDIT3                 1211
#define IDC_BLEND1_EDIT                 1211
#define IDC_GAPRATIO_COMBO              1212
#define IDC_TRANSEL_COMBO               1212
#define IDC_EDIT_INT_WIDTH              1212
#define IDC_BLEND_SCROLLBAR3            1212
#define IDC_BLEND1_SCROLLBAR            1212
#define IDC_EDIT_ADDR1                  1213
#define IDC_PTNWRMASK_CHECK             1213
#define IDC_RADIO_MUL8                  1213
#define IDC_OVLYMODE_COMBO2             1213
#define IDC_OVERLAP_COMBO               1213
#define IDC_EDIT_ADDR2                  1214
#define IDC_MAPPTN_COMBO                1214
#define IDC_SRCEXTEND_CHECK             1214
#define IDC_RADIO_MUL16                 1214
#define IDC_B1FIRST_CHECK3              1214
#define IDC_B1FIRST_CHECK               1214
#define IDC_EDIT_ADDR3                  1215
#define IDC_LIST_CLOCK                  1215
#define IDC_RADIO_SEP                   1215
#define IDC_B0ENABLE_CHECK              1215
#define IDC_EDIT_ADDR4                  1216
#define IDC_SRCSPAN_EDIT                1216
#define IDC_EDIT_CLKIN                  1216
#define IDC_BGENABLE_CHECK              1216
#define IDC_EDIT_ADDR5                  1217
#define IDC_CLIP_SPY_SCROLLBAR          1217
#define IDC_EDIT_CLKOUT                 1217
#define IDC_BG_UPDATE_BUTTON            1217
#define IDC_UPDATE_BG_BUTTON            1217
#define IDC_EDIT_ADDR6                  1218
#define IDC_CLIP_EPX_EDIT               1218
#define IDC_EDIT_MCLK                   1218
#define IDC_BGCOLOR_EDIT                1218
#define IDC_EDIT_ADDR7                  1219
#define IDC_CLIP_EPY_EDIT               1219
#define IDC_EDIT_M                      1219
#define IDC_SET_BG_BUTTON               1219
#define IDC_EDIT_ADDR1_VALUE1           1220
#define IDC_CLIP_EPX_SCROLLBAR          1220
#define IDC_EDIT_N                      1220
#define IDC_CHECK1                      1220
#define IDC_SPECIAL_EN_CHECK            1220
#define IDC_CHECK_SIFCAP                1220
#define IDC_GP_FIRST_CHECK              1220
#define IDC_COMM_CODE_EN_CHECK          1220
#define IDC_EDIT_ADDR1_VALUE2           1221
#define IDC_CLIP_EPY_SCROLLBAR          1221
#define IDC_CHECK_CLK_ALL               1221
#define IDC_SCROLLBAR2                  1221
#define IDC_VOFFSET_SCROLLBAR           1221
#define IDC_IPP_WINX_SCROLLBAR          1221
#define IDC_BARW_SCROLLBAR              1221
#define IDC_EDIT_ADDR1_VALUE3           1222
#define IDC_LIST_RESET                  1222
#define IDC_SCROLLBAR3                  1222
#define IDC_UTOP_SCROLLBAR              1222
#define IDC_IPP_WINY_SCROLLBAR          1222
#define IDC_BARH_SCROLLBAR              1222
#define IDC_EDIT_ADDR2_VALUE1           1223
#define IDC_CHECK_RESET_ALL             1223
#define IDC_SCROLLBAR4                  1223
#define IDC_UBTM_SCROLLBAR              1223
#define IDC_IPP_WINW_SCROLLBAR          1223
#define IDC_IMGW_SCROLLBAR              1223
#define IDC_EDIT_ADDR2_VALUE2           1224
#define IDC_EDIT_OD0                    1224
#define IDC_SCROLLBAR5                  1224
#define IDC_VTOP_SCROLLBAR              1224
#define IDC_IPP_WINH_SCROLLBAR          1224
#define IDC_IMGH_SCROLLBAR              1224
#define IDC_EDIT_ADDR2_VALUE3           1225
#define IDC_EDIT_OD1                    1225
#define IDC_SCROLLBAR6                  1225
#define IDC_VBTM_SCROLLBAR              1225
#define IDC_IPP_DSW_SCROLLBAR           1225
#define IDC_EDIT_ADDR3_VALUE1           1226
#define IDC_EDIT_CLKDIV                 1226
#define IDC_EDIT6                       1226
#define IDC_VBTM_EDIT                   1226
#define IDC_IPP_DSH_EDIT                1226
#define IDC_BARH_EDIT                   1226
#define IDC_RPT_EX_EDIT                 1226
#define IDC_EDIT_ADDR3_VALUE2           1227
#define IDC_CHECK_CAP_RD_DATA           1227
#define IDC_EDIT_TIME                   1227
#define IDC_EDIT_ADDR3_VALUE3           1228
#define IDC_CHECK3                      1228
#define IDC_FRAME_EN_CHECK              1228
#define IDC_LFO_EN_CHECK                1228
#define IDC_CHECK_RECAP                 1228
#define IDC_STATIC_ADDR1                1229
#define IDC_EDIT7                       1229
#define IDC_DDROP_EDIT                  1229
#define IDC_IPP_CSW_EDIT                1229
#define IDC_HSTARTE_EDIT                1229
#define IDC_RPT_SY_EDIT                 1229
#define IDC_STATIC_ADDR2                1230
#define IDC_CHECK_CLK_MONITOR           1230
#define IDC_EDIT8                       1230
#define IDC_CDROP_EDIT                  1230
#define IDC_IPP_CSH_EDIT                1230
#define IDC_VSTARTA_EDIT                1230
#define IDC_RPT_EY_EDIT                 1230
#define IDC_STATIC_ADDR3                1231
#define IDC_CHECK_CLK_AUTO              1231
#define ID_BUTTON_TEST_DELAYSEL         1231
#define IDC_CHECK4                      1231
#define IDC_DPS_EN_CHECK                1231
#define IDC_DPDC_EN_CHECK               1231
#define IDC_CHECK_SIMP_HEAD             1231
#define IDC_BUTTON_POWERON              1232
#define ID_BUTTON_TEST_REGCONREAD       1232
#define IDC_CHECK5                      1232
#define IDC_CPDS_EN_CHECK               1232
#define IDC_RGB_GAMMA_EN_CHECK          1232
#define IDC_CHECK_TIME_MODE             1232
#define IDC_CHECK_RECAP3                1232
#define IDC_CHECK_AVI                   1232
#define IDC_BUTTON_POWEROFF             1233
#define IDC_RESTPANEL_BUTTON            1233
#define IDC_BUTTON_GET_ENV              1233
#define IDC_BUTTON_TCR                  1233
#define ID_HOSTIFREFRESH_BUTTON         1233
#define IDC_CHECK6                      1233
#define IDC_CPUS_EN_CHECK               1233
#define IDC_CHECK_AVI2                  1233
#define IDC_CHECK_TEST_RECAP            1233
#define IDC_STATIC_ADDR6                1234
#define ID_HOSTIFBUSSPEEDTEST_BUTTON    1234
#define IDC_CHECK7                      1234
#define IDC_TMS_EN_CHECK                1234
#define IDC_MATRIX_EN_CHECK             1234
#define IDC_CHECK_DEC_WR_DATA           1234
#define IDC_STATIC_ADDR7                1235
#define IDC_CHECK8                      1235
#define IDC_DPH_BP_EN_CHECK             1235
#define IDC_Y_GAMMA_EN_CHECK            1235
#define IDC_STATIC_ADDR8                1236
#define IDC_CHECK9                      1236
#define IDC_TMH_BP_EN_CHECK             1236
#define IDC_RGB_GAIN_EN_CHECK           1236
#define IDC_STATIC_ADDR9                1237
#define IDC_CHECK10                     1237
#define IDC_DPV_BP_EN_CHECK             1237
#define IDC_GLOBAL_GAIN_EN_CHECK        1237
#define IDC_EDIT_ADDR4_VALUE1           1238
#define IDC_CHECK11                     1238
#define IDC_TMV_BP_EN_CHECK             1238
#define IDC_AWB_EN_CHECK                1238
#define IDC_EDIT_ADDR4_VALUE2           1239
#define IDC_CHECK12                     1239
#define IDC_CPUH_BP_EN_CHECK            1239
#define IDC_NOISE_Y_EN_CHECK            1239
#define IDC_EDIT_ADDR4_VALUE3           1240
#define IDC_CHECK13                     1240
#define IDC_CPDH_BP_EN_CHECK            1240
#define IDC_NOISE_UV_EN_CHECK           1240
#define IDC_EDIT_ADDR5_VALUE1           1241
#define IDC_CHECK14                     1241
#define IDC_CPUV_BP_EN_CHECK            1241
#define IDC_AUTO_FOCUS_EN_CHECK         1241
#define IDC_EDIT_ADDR5_VALUE2           1242
#define IDC_CHECK15                     1242
#define IDC_CPDV_BP_EN_CHECK            1242
#define IDC_BLACK_IMAGE_EN_CHECK        1242
#define IDC_EDIT_ADDR5_VALUE3           1243
#define IDC_SCROLLBAR7                  1243
#define IDC_IPP_DSH_SCROLLBAR           1243
#define IDC_EDIT_ADDR6_VALUE1           1244
#define IDC_SCROLLBAR8                  1244
#define IDC_IPP_CSW_SCROLLBAR           1244
#define IDC_EDIT_ADDR6_VALUE2           1245
#define IDC_EDIT9                       1245
#define IDC_IMGW_EDIT                   1245
#define IDC_IPP_TSW_EDIT                1245
#define IDC_EDIT_ADDR6_VALUE3           1246
#define IDC_EDIT10                      1246
#define IDC_IMGH_EDIT                   1246
#define IDC_IPP_TSH_EDIT                1246
#define IDC_EDIT_ADDR7_VALUE1           1247
#define IDC_SCROLLBAR9                  1247
#define IDC_WINX_SCROLLBAR              1247
#define IDC_IPP_CSH_SCROLLBAR           1247
#define IDC_EDIT_ADDR7_VALUE2           1248
#define IDC_EDIT11                      1248
#define IDC_WINX_EDIT                   1248
#define IDC_LAX_EDIT                    1248
#define IDC_FEMM_EDIT                   1248
#define IDC_EDIT_ADDR7_VALUE3           1249
#define IDC_SCROLLBAR10                 1249
#define IDC_WINY_SCROLLBAR              1249
#define IDC_IPP_TSW_SCROLLBAR           1249
#define IDC_BAR_AEWIN_HEIGHT            1250
#define IDC_EDIT12                      1250
#define IDC_WINY_EDIT                   1250
#define IDC_LAY_EDIT                    1250
#define IDC_FEMX1_EDIT                  1250
#define IDC_STATIC_START                1251
#define IDC_SCROLLBAR11                 1251
#define IDC_WINW_SCROLLBAR              1251
#define IDC_IPP_TSH_SCROLLBAR           1251
#define IDC_STATIC_STOP                 1252
#define IDC_SCROLLBAR12                 1252
#define IDC_WINH_SCROLLBAR              1252
#define IDC_LAX_SCROLLBAR               1252
#define IDC_EDIT_WIN_START              1253
#define IDC_EDIT13                      1253
#define IDC_WINW_EDIT                   1253
#define IDC_LAW_EDIT                    1253
#define IDC_FEM_MIN_EDIT                1253
#define IDC_EDIT_WIN_STOP               1254
#define IDC_STATIC_FLK_STAT             1254
#define IDC_EDIT14                      1254
#define IDC_WINH_EDIT                   1254
#define IDC_LAH_EDIT                    1254
#define IDC_VSTARTB_EDIT                1254
#define IDC_EDIT_AFL_STAT               1255
#define IDC_SCROLLBAR13                 1255
#define IDC_TMSW_SCROLLBAR              1255
#define IDC_LAY_SCROLLBAR               1255
#define IDC_EDIT_QHISTO                 1256
#define IDC_SCROLLBAR14                 1256
#define IDC_TMSH_SCROLLBAR              1256
#define IDC_LAW_SCROLLBAR               1256
#define IDC_STATIC_QHISTOGRAM           1257
#define IDC_EDIT15                      1257
#define IDC_TMSW_EDIT                   1257
#define IDC_LADX_EDIT                   1257
#define IDC_HREF_START_EDIT             1257
#define IDC_VSTARTC_EDIT                1257
#define IDC_EDIT_XCUR                   1258
#define IDC_EDIT16                      1258
#define IDC_TMSH_EDIT                   1258
#define IDC_LADY_EDIT                   1258
#define IDC_HREF_LENGTH_EDIT            1258
#define IDC_VSTARTD_EDIT                1258
#define IDC_EDIT_XAVG                   1259
#define IDC_SCROLLBAR15                 1259
#define IDC_DPSW_SCROLLBAR              1259
#define IDC_LAH_SCROLLBAR               1259
#define IDC_EDIT_EDGESUM                1260
#define IDC_SCROLLBAR16                 1260
#define IDC_DPSH_SCROLLBAR              1260
#define IDC_LADX_SCROLLBAR              1260
#define IDC_EDIT_YMEAN                  1261
#define IDC_EDIT17                      1261
#define IDC_DPSW_EDIT                   1261
#define IDC_LAMW_EDIT                   1261
#define IDC_VREF_START_EDIT             1261
#define IDC_VSTARTE_EDIT                1261
#define IDC_STATIC_XCUR                 1262
#define IDC_EDIT18                      1262
#define IDC_DPSH_EDIT                   1262
#define IDC_LAMH_EDIT                   1262
#define IDC_VREF_STOP_EDIT              1262
#define IDC_YBOT_EDIT                   1262
#define IDC_STATIC_XAVG                 1263
#define IDC_SCROLLBAR17                 1263
#define IDC_CPSW_SCROLLBAR              1263
#define IDC_LADY_SCROLLBAR              1263
#define IDC_STATIC_EDGESUM              1264
#define IDC_SCROLLBAR18                 1264
#define IDC_CPSH_SCROLLBAR              1264
#define IDC_LAMW_SCROLLBAR              1264
#define IDC_STATIC_YMEAN                1265
#define IDC_EDIT19                      1265
#define IDC_CPSW_EDIT                   1265
#define IDC_OB_REG_EDIT                 1265
#define IDC_YTOP_EDIT                   1265
#define IDC_HUE_COS_EDIT                1265
#define IDC_EDIT_YTARGET                1266
#define IDC_EDIT20                      1266
#define IDC_CPSH_EDIT                   1266
#define IDC_QTOP_EDIT                   1266
#define IDC_HUE_SIN_EDIT                1266
#define IDC_STATIC_YTARGET              1267
#define IDC_EDIT21                      1267
#define IDC_TMS_HW1_EDIT                1267
#define IDC_ITOP_EDIT                   1267
#define IDC_ISP_SAT_EDIT                1267
#define IDC_VSYNC_DELAY_VALUE_EDIT      1267
#define IDC_BUTTON_REFRESH              1268
#define IDC_EDIT22                      1268
#define IDC_TMS_VH1_EDIT                1268
#define IDC_HUE_Y_EDIT                  1268
#define IDC_EDIT_YTHD                   1269
#define IDC_EDIT23                      1269
#define IDC_TMS_HW2_EDIT                1269
#define IDC_BUTTON_RUDE_SET             1269
#define IDC_AWB_GAIN_MIN_EDIT           1269
#define IDC_HUE_U_EDIT                  1269
#define IDC_STATIC_YTHD                 1270
#define IDC_EDIT24                      1270
#define IDC_TMS_HS1_EDIT                1270
#define IDC_AWB_GAIN_MAX_EDIT           1270
#define IDC_HUE_V_EDIT                  1270
#define IDC_BUTTON_ENH_SET              1270
#define IDC_CHECK_TESTBAR               1271
#define IDC_EDIT25                      1271
#define IDC_TMS_HS2_EDIT                1271
#define IDC_AWB_STEP_EDIT               1271
#define IDC_RPT_CNT_EDIT                1271
#define IDC_BUTTON_CAP_DLY              1271
#define IDC_CHECK_SHARPEDGE             1272
#define IDC_EDIT26                      1272
#define IDC_TMS_HC_EDIT                 1272
#define IDC_AWB_THD1_EDIT               1272
#define IDC_H_STEP_EDIT                 1272
#define IDC_BUTTON_RUDE_SET2            1272
#define IDC_BUTTON_CAP_DLY_FEED         1272
#define IDC_CHECK_LENFALL               1273
#define IDC_EDIT27                      1273
#define IDC_TMS_VH2_EDIT                1273
#define IDC_AWB_THD2_EDIT               1273
#define IDC_V_STEP_EDIT                 1273
#define IDC_CHECK_DPD                   1274
#define IDC_EDIT28                      1274
#define IDC_TMS_VS1_EDIT                1274
#define IDC_RMEAN_EDIT                  1274
#define IDC_PCDEMO_CHECK                1275
#define IDC_CHECK_RGB_GAMMA             1275
#define IDC_BYPASSSTARTCOORX_EDIT       1275
#define IDC_EDIT29                      1275
#define IDC_TMS_VS2_EDIT                1275
#define IDC_GMEAN_EDIT                  1275
#define IDC_OPEN_CHECK                  1276
#define IDC_CHECK_COLOR_COR             1276
#define IDC_BYPASSENDCOORX_EDIT         1276
#define IDC_EDIT30                      1276
#define IDC_TMS_VC_EDIT                 1276
#define IDC_BMEAN_EDIT                  1276
#define IDC_POWERON_CHECK               1277
#define IDC_CHECK_Y_GAMMA               1277
#define IDC_BYPASSLINECOLOR_EDIT        1277
#define IDC_EDIT31                      1277
#define IDC_DPS_HW1_EDIT                1277
#define IDC_YMEAN_EDIT                  1277
#define IDC_VOLUME_SLIDER               1278
#define IDC_CHECK_DIG_GAIN              1278
#define IDC_BYPASSSTARTCOORY_EDIT       1278
#define IDC_EDIT32                      1278
#define IDC_DPS_VH1_EDIT                1278
#define IDC_AF_STATUS_EDIT              1278
#define IDC_CHECK_AUTO_FLK              1279
#define IDC_EDIT33                      1279
#define IDC_DPS_HW2_EDIT                1279
#define IDC_EDGE_SUM_EDIT               1279
#define IDC_CHECK_AWB                   1280
#define IDC_EDIT34                      1280
#define IDC_DPS_VH2_EDIT                1280
#define IDC_DPT_THD_EDIT                1280
#define IDC_CHECK_Y_NOISEREMOVE         1281
#define IDC_EDIT35                      1281
#define IDC_DPS_HS1_EDIT                1281
#define IDC_DPT_UV_THD_EDIT             1281
#define IDC_CHECK_UV_NOISEREMOVE        1282
#define IDC_EDIT36                      1282
#define IDC_DPS_VS1_EDIT                1282
#define IDC_BL_R_OFT_EDIT               1282
#define IDC_CHECK_YUV_EN                1283
#define IDC_EDIT37                      1283
#define IDC_DPS_HS2_EDIT                1283
#define IDC_BL_B_OFT_EDIT               1283
#define IDC_CHECK_HISTO                 1284
#define IDC_EDIT38                      1284
#define IDC_DPS_VS2_EDIT                1284
#define IDC_FEMP_EDIT                   1284
#define IDC_CHECK_AUTO_FOCUS            1285
#define IDC_EDIT39                      1285
#define IDC_DPS_HC_EDIT                 1285
#define IDC_BL_G1_OFT_EDIT              1285
#define IDC_BUTTON_JUDGE_ENV            1286
#define IDC_EDIT40                      1286
#define IDC_DPS_VC_EDIT                 1286
#define IDC_DPS_VC_EDITBOX              1286
#define IDC_BUTTON_AE_SIM               1287
#define IDC_EDIT41                      1287
#define IDC_CPDS_HW1_EDIT               1287
#define IDC_BUTTON_SET_ENV              1288
#define IDC_EDIT42                      1288
#define IDC_CPDS_HW2_EDIT               1288
#define IDC_RESP_COMBO                  1289
#define IDC_HEADNUM_COMBO               1289
#define IDC_GAMMASEL_COMBO              1289
#define IDC_COMBO_ENV                   1289
#define IDC_DISPFMT_COMBO               1289
#define IDC_EDIT43                      1289
#define IDC_CPDS_HS1_EDIT               1289
#define IDC_EDIT44                      1290
#define IDC_CPDS_HS2_EDIT               1290
#define IDC_FEMX2_EDIT                  1290
#define IDC_EDIT45                      1291
#define IDC_CPDS_HC_EDIT                1291
#define IDC_FEM_MAX_EDIT                1291
#define IDC_SCRBAR_IMAGE_HEIGHT         1292
#define IDC_EDIT46                      1292
#define IDC_CPUS_HW1_EDIT               1292
#define IDC_CENX_EDIT                   1292
#define IDC_SCRBAR_WIN_WIDTH            1293
#define IDC_EDIT47                      1293
#define IDC_CPUS_HW2_EDIT               1293
#define IDC_CENY_EDIT                   1293
#define IDC_SCRBAR_WIN_HEIGHT           1294
#define IDC_EDIT48                      1294
#define IDC_CPUS_HS_EDIT                1294
#define IDC_F2_EDIT                     1294
#define IDC_SCRBAR_CAP_WIDTH            1295
#define IDC_EDIT49                      1295
#define IDC_CPDS_VH1_EDIT               1295
#define IDC_LINE_CNT_EDIT               1295
#define IDC_SCRBAR_CAP_HEIGHT           1296
#define IDC_EDIT50                      1296
#define IDC_CPDS_VH2_EDIT               1296
#define IDC_LINE_START_EDIT             1296
#define IDC_SCRBAR_DISP_WIDTH           1297
#define IDC_EDIT51                      1297
#define IDC_CPDS_VS1_EDIT               1297
#define IDC_AF_STAT_EDIT                1297
#define IDC_SCRBAR_DISP_HEIGHT          1298
#define IDC_EDIT52                      1298
#define IDC_CPDS_VS2_EDIT               1298
#define IDC_LINE_STEP_EDIT              1298
#define IDC_SCRBAR_THUMB_WIDTH          1299
#define IDC_EDIT53                      1299
#define IDC_CPDS_VC_EDIT                1299
#define IDC_TAIL_BLANK_EDIT             1299
#define IDC_SCRBAR_THUMB_HEIGHT         1300
#define IDC_EDIT54                      1300
#define IDC_CPUS_VH1_EDIT               1300
#define IDC_RGAIN_EDIT                  1300
#define IDC_SCRBAR_STARTX               1301
#define IDC_EDIT55                      1301
#define IDC_CPUS_VH2_EDIT               1301
#define IDC_GGAIN_EDIT                  1301
#define IDC_SCRBAR_STARTY               1302
#define IDC_EDIT56                      1302
#define IDC_CPUS_VS_EDIT                1302
#define IDC_BGAIN_EDIT                  1302
#define IDC_SCRBAR_U_OFFSET             1303
#define IDC_RESET_BUTTON                1303
#define IDC_SCRBAR_V_OFFSET             1304
#define IDC_LAMH_SCROLLBAR              1304
#define IDC_SCRBAR_U_UP                 1305
#define IDC_Layer_A_BUTTON              1305
#define IDC_LAYER_A_BUTTON              1305
#define IDC_SCRBAR_U_DOWN               1306
#define IDC_IPP_WIN_BUTTON              1306
#define IDC_SCRBAR_V_DOWN               1307
#define IDC_THUMB_SIZER_BUTTON          1307
#define IDC_SCRBAR_V_UP                 1308
#define IDC_SET_LAYER_A_BUTTON          1308
#define IDC_EDIT_U_OFFSET               1309
#define IDC_SENSOR_EN_CHECK             1309
#define IDC_CMDINDEX_EDIT               1310
#define IDC_IBUFSIZE_EDIT               1310
#define IDC_RS_EDIT                     1310
#define IDC_BGX_EDIT                    1310
#define IDC_EDIT_HA                     1310
#define IDC_EDIT_V_OFFSET               1310
#define IDC_DISPCHAR_EDIT               1310
#define IDC_GPIOCONFIG_EDIT             1310
#define IDC_POLARITY_EN_CHECK           1310
#define IDC_CMDARGU_EDIT                1311
#define IDC_RAMSTART_EDIT               1311
#define IDC_DATAFMT_COMBO               1311
#define IDC_COMBO_AE_MODE               1311
#define IDC_EDIT_U_DOWN                 1311
#define IDC_FONTOPTION_COMBO            1311
#define IDC_GPIOMODE_EDIT               1311
#define IDC_SYNC_GEN_EN_CHECK           1311
#define IDC_CMDRESP_EDIT                1312
#define IDC_RAMEND_EDIT                 1312
#define IDC_STARTXPOS_EDIT              1312
#define IDC_EDIT_HB                     1312
#define IDC_EDIT_U_UP                   1312
#define IDC_GPIODIR_EDIT                1312
#define IDC_STARTYPOS_EDIT              1313
#define IDC_EDIT_HC                     1313
#define IDC_EDIT_V_DOWN                 1313
#define IDC_GPIOWRITEVALUE_EDIT         1313
#define IDC_ENDXPOS_EDIT                1314
#define IDC_EDIT_HD                     1314
#define IDC_EDIT_V_UP                   1314
#define IDC_GPIOREADVALUE_EDIT          1314
#define IDC_SENSOR_RESET_BUTTON         1314
#define IDC_ENDYPOS_EDIT                1315
#define IDC_EDIT_HE                     1315
#define IDC_OB_REG_EN_CHECK             1315
#define IDC_EDIT_VA                     1316
#define IDC_SNR_CLK_INV_CHECK           1316
#define IDC_SETCFG_BUTTON               1317
#define IDC_EDIT_VB                     1317
#define IDC_SI_CLK_RVS_CHECK            1317
#define IDC_DATA0_EDIT                  1318
#define IDC_EDIT_VC                     1318
#define IDC_SYNC_OUT_EN_CHECK           1318
#define IDC_DATA1_EDIT                  1319
#define IDC_EDIT_VD                     1319
#define IDC_I2C_SEL_COMBO               1319
#define IDC_DATA2_EDIT                  1320
#define IDC_EDIT_VE                     1320
#define IDC_YUV_FMT_COMBO               1320
#define IDC_DATA3_EDIT                  1321
#define IDC_COMBO9                      1321
#define IDC_EDGE_CHOS_COMBO             1321
#define IDC_FIRST_LINE_COMBO            1321
#define IDC_DATA4_EDIT                  1322
#define IDC_DATA5_EDIT                  1323
#define IDC_EDGE_EN_CHECK               1323
#define IDC_DATA6_EDIT                  1324
#define IDC_SIF_FMT_COMBO               1324
#define IDC_DATA7_EDIT                  1325
#define IDC_FILTER_COMBO                1325
#define IDC_PANELSEL_COMBO              1326
#define IDC_IMAGE_MODE_COMBO            1326
#define IDC_UPDATEBWIN_BUTTON           1327
#define IDC_UPDATE_B0_BUTTON            1327
#define IDC_AF_LINE_CHECK               1327
#define IDC_SDCMD_CHECK                 1328
#define IDC_DATA8_EDIT                  1328
#define IDC_UPDATEBWIN_BUTTON2          1328
#define IDC_UPDATE_B1_BUTTON            1328
#define IDC_GLOBAL_GAIN_VAL_EDIT        1328
#define IDC_SDCMDINDEX_CHECK            1329
#define IDC_DATA9_EDIT                  1329
#define IDC_VALUE00_EDIT                1329
#define IDC_GLOBAL_GAIN_STEP_COMBO      1329
#define IDC_SDDATADIREC_CHECK           1330
#define IDC_DATA10_EDIT                 1330
#define IDC_GLOBAL_GAIN_DLY_COMBO       1330
#define IDC_DATAPRES_CHECK              1331
#define IDC_DATA11_EDIT                 1331
#define IDC_VALUE01_EDIT                1331
#define IDC_CR_ADJ_EDIT                 1331
#define IDC_STOMODDMA_CHECK             1332
#define IDC_DATA12_EDIT                 1332
#define IDC_VALUE02_EDIT                1332
#define IDC_CB_ADJ_EDIT                 1332
#define IDC_DATA13_EDIT                 1333
#define IDC_VALUE03_EDIT                1333
#define IDC_CR_OFT_EDIT                 1333
#define IDC_AUTOCMD12_CHECK             1334
#define IDC_DATA14_EDIT                 1334
#define IDC_VALUE04_EDIT                1334
#define IDC_CB_OFT_EDIT                 1334
#define IDC_STOMODSPI_CHECK             1335
#define IDC_DATA15_EDIT                 1335
#define IDC_VALUE05_EDIT                1335
#define IDC_MAT11_EDIT                  1335
#define IDC_STOMODTRANSWIDTH_CHECK      1336
#define IDC_VALUE06_EDIT                1336
#define IDC_MAT12_EDIT                  1336
#define IDC_VALUE07_EDIT                1337
#define IDC_MAT13_EDIT                  1337
#define IDC_WRC_SCROLLBAR               1338
#define IDC_VALUE08_EDIT                1338
#define IDC_ROFT_EDIT                   1338
#define IDC_DHC_SCROLLBAR               1339
#define IDC_VALUE09_EDIT                1339
#define IDC_MAT21_EDIT                  1339
#define IDC_RSC_SCROLLBAR               1340
#define IDC_VALUE10_EDIT                1340
#define IDC_MAT22_EDIT                  1340
#define IDC_RAC_SCROLLBAR               1341
#define IDC_VALUE11_EDIT                1341
#define IDC_MAT23_EDIT                  1341
#define IDC_ROC_SCROLLBAR               1342
#define IDC_VALUE12_EDIT                1342
#define IDC_GOFT_EDIT                   1342
#define IDC_WSC_EDIT                    1343
#define IDC_VALUE13_EDIT                1343
#define IDC_MAT31_EDIT                  1343
#define IDC_WRC_EDIT                    1344
#define IDC_VALUE14_EDIT                1344
#define IDC_MAT32_EDIT                  1344
#define IDC_DHC_EDIT                    1345
#define IDC_VALUE15_EDIT                1345
#define IDC_MAT33_EDIT                  1345
#define IDC_RSC_EDIT                    1346
#define IDC_VALUE16_EDIT                1346
#define IDC_BOFT_EDIT                   1346
#define IDC_RAC_EDIT                    1347
#define IDC_YSTART0_EDIT                1347
#define IDC_ROC_EDIT                    1348
#define IDC_YSTART1_EDIT                1348
#define IDC_BIASX_SCROLLBAR             1349
#define IDC_YSTART2_EDIT                1349
#define IDC_BIASX_EDIT                  1350
#define IDC_YSTART3_EDIT                1350
#define IDC_BLKCNT_EDIT                 1351
#define IDC_BIASY_SCROLLBAR             1351
#define IDC_YSTART4_EDIT                1351
#define IDC_BLKSIZE_EDIT                1352
#define IDC_BIASY_EDIT                  1352
#define IDC_EDIT_GAMMA0                 1352
#define IDC_FONTX_EDIT                  1352
#define IDC_TRANSADDR_EDIT              1353
#define IDC_CSSEL_COMBO                 1353
#define IDC_EDIT_GAMMA2                 1353
#define IDC_BUSTYPE_COMBO               1354
#define IDC_EDIT_GAMMA3                 1354
#define IDC_HEADEN_CHECK                1355
#define IDC_EDIT_GAMMA4                 1355
#define IDC_RSHEN_CHECK                 1356
#define IDC_EDIT_GAMMA5                 1356
#define IDC_DMAPCONV_CHECK              1357
#define IDC_EDIT_GAMMA6                 1357
#define IDC_BIASDIVX_CHECK              1358
#define IDC_EDIT_GAMMA7                 1358
#define IDC_EDIT_GAMMA8                 1359
#define IDC_EDIT_GAMMA9                 1360
#define IDC_BIASDIVY_CHECK              1361
#define IDC_EDIT_GAMMA10                1361
#define IDC_OKCM_CHECK                  1362
#define IDC_EDIT_GAMMA11                1362
#define IDC_B0OKCM_CHECK                1362
#define IDC_LAYERAEN_CHECK              1363
#define IDC_EDIT_GAMMA12                1363
#define IDC_BGY_SCROLLBAR               1364
#define IDC_EDIT_GAMMA13                1364
#define IDC_BGW_SCROLLBAR               1365
#define IDC_EDIT_GAMMA14                1365
#define IDC_BGH_SCROLLBAR               1366
#define IDC_EDIT_GAMMA15                1366
#define IDC_BGY_EDIT                    1367
#define IDC_EDIT_GAMMA16                1367
#define IDC_BGW_EDIT                    1368
#define IDC_EDIT_GAMMA1                 1368
#define IDC_BGH_EDIT                    1369
#define IDC_CBO_GAMMA                   1369
#define IDC_DEDLY_SCROLLBAR             1370
#define IDC_DISPSTR_EDIT                1370
#define IDC_YSTART5_EDIT                1370
#define IDC_DEINTV_SCROLLBAR            1371
#define IDC_FONTSY_SCROLLBAR            1371
#define IDC_YSTART6_EDIT                1371
#define IDC_LINEINTV_SCROLLBAR          1372
#define IDC_PREDISP_BUTTON              1372
#define IDC_YSTART7_EDIT                1372
#define IDC_OKCM_CHECK2                 1373
#define IDC_B1OKCM_CHECK                1373
#define IDC_YSTART8_EDIT                1373
#define IDC_DEDLY_EDIT                  1374
#define IDC_FONTY_EDIT                  1374
#define IDC_YSLOPE0_EDIT                1374
#define IDC_DEINTV_EDIT                 1375
#define IDC_SKIP_DISP                   1375
#define IDC_YSLOPE1_EDIT                1375
#define IDC_LINEINTV_EDIT               1376
#define IDC_SKIP_DISP_NEXT              1376
#define IDC_YSLOPE2_EDIT                1376
#define IDC_SKIP_DISP_NEXT2             1377
#define IDC_SKIP_DEC                    1377
#define IDC_YSLOPE3_EDIT                1377
#define IDC_CAP_AUTO                    1378
#define IDC_SKIP_DISP2                  1378
#define IDC_YSLOPE4_EDIT                1378
#define IDC_YSLOPE5_EDIT                1379
#define IDC_RADIO_MUL8_HOSTIF           1380
#define IDC_YSLOPE6_EDIT                1380
#define IDC_RADIO_MUL16_HOSTIF          1381
#define IDC_YSLOPE7_EDIT                1381
#define IDC_RADIO_SEP_HOSTIF            1382
#define IDC_YSLOPE8_EDIT                1382
#define IDC_BRIGHT_RADIO                1383
#define IDC_GAMMA_GET_BUTTON            1383
#define IDC_CONTRAST_RADIO              1384
#define IDC_ANTI_FLICKER_EN_CHECK       1384
#define IDC_AF_INT_FREQ_COMBO           1385
#define IDC_AE_WEIGHT_COMBO             1386
#define IDC_WIN_WEIGHT_COMBO            1387
#define IDC_AWB_MODE_COMBO              1388
#define IDC_AWB_WIN_COMBO               1389
#define IDC_EDGE_KERNEL_COMBO           1390
#define IDC_TEST_BAR_EN_CHECK           1395
#define IDC_FILTER_MODE_COMBO           1396
#define IDC_TEST_BAR_COMBO              1397
#define IDC_FOCUS_INT_EN_CHECK          1398
#define IDC_FLICKER_INT_EN_CHECK        1399
#define IDC_Y_MEAN_INT_EN_CHECK         1400
#define IDC_HIST_EFFECT_EN_CHECK        1401
#define IDC_HIST_MANUAL_EN_CHECK        1402
#define IDC_BL_G2_OFT_EDIT              1403
#define IDC_HIST_GAIN_EDIT              1404
#define IDC_YMEAN_TGT_EDIT              1405
#define IDC_EDIT60                      1406
#define IDC_YMEAN_THD_EDIT              1406
#define IDC_HIST_R00_EDIT               1406
#define IDC_GET_BLANK_BUTTON            1407
#define IDC_WIN_SIZE_BUTTON             1410
#define IDC_IMAGE_SIZE_BUTTON           1411
#define IDC_T_SIZER_BUTTON              1412
#define IDC_D_SIZER_BUTTON              1413
#define IDC_HIST_EN_CHECK               1414
#define IDC_HIST_X_CUR_EDIT             1415
#define IDC_HIST_X_AVG_EDIT             1416
#define IDC_HIST_Q_EDIT                 1417
#define IDC_HIST_R08_EDIT               1418
#define IDC_HIST_R10_EDIT               1419
#define IDC_HIST_R18_EDIT               1420
#define IDC_HIST_R20_EDIT               1421
#define IDC_HIST_R28_EDIT               1422
#define IDC_HIST_R30_EDIT               1423
#define IDC_HIST_R38_EDIT               1424
#define IDC_HIST_R40_EDIT               1425
#define IDC_HIST_R48_EDIT               1426
#define IDC_HIST_R50_EDIT               1427
#define IDC_HIST_R58_EDIT               1428
#define IDC_HIST_R60_EDIT               1429
#define IDC_HIST_R68_EDIT               1430
#define IDC_HIST_R70_EDIT               1431
#define IDC_HIST_R78_EDIT               1432
#define IDC_HIST_R80_EDIT               1433
#define IDC_HIST_R88_EDIT               1434
#define IDC_HIST_R90_EDIT               1435
#define IDC_HIST_R98_EDIT               1436
#define IDC_HIST_RA0_EDIT               1437
#define IDC_HIST_RA8_EDIT               1438
#define IDC_HIST_RB0_EDIT               1439
#define IDC_HIST_RB8_EDIT               1440
#define IDC_HIST_RC0_EDIT               1441
#define IDC_HIST_RC8_EDIT               1442
#define IDC_HIST_RD0_EDIT               1443
#define IDC_HIST_RD8_EDIT               1444
#define IDC_HIST_RE0_EDIT               1445
#define IDC_HIST_RE8_EDIT               1446
#define IDC_HIST_RF0_EDIT               1447
#define IDC_HIST_RF8_EDIT               1448
#define IDC_HIST_GET_BUTTON             1449
#define IDC_HIST_SET_BUTTON             1450
#define IDC_VSYNC_RST_CHECK             1451
#define IDC_CHECK2                      1452
#define IDC_HUE_EN_CHECK                1452
#define IDC_HEAD_RPT_EN_CHECK           1452
#define IDC_SNR_PCLK_EN_CHECK           1452
#define IDC_HUE_COS_SCROLLBAR           1453
#define IDC_HUE_SIN_SCROLLBAR           1454
#define IDC_ISP_SAT_SCROLLBAR           1455
#define IDC_HUE_Y_SCROLLBAR             1456
#define IDC_HUE_U_SCROLLBAR             1457
#define IDC_SCROLLBAR24                 1458
#define IDC_HUE_V_SCROLLBAR             1458
#define IDC_DISP_STR_BUTTON             1459
#define IDC_C_SIZER_TEST_BUTTON         1460
#define IDC_H_STEP_SCROLLBAR            1461
#define IDC_V_STEP_SCROLLBAR            1462
#define IDC_HIST_EN_BUTTON              1463
#define IDC_FIFO_VSYNC_EN_CHECK         1466
#define IDC_CHECK19                     1467
#define IDC_VSYNC_DELAY_EN_CHECK        1467
#define IDC_CHECK16                     1468
#define IDC_PCLK_NEG_CHECK              1468
#define IDC_AE_MODE_COMBO               1469
#define IDC_COMBO11                     1470
#define IDC_ENV_SEL_COMBO               1470
#define IDC_COMBO_COM                   1470
#define IDC_COMBO_CMD                   1471
#define IDC_GET_ENV_BUTTON              1472
#define IDC_SIM_AE_BUTTON               1473
#define IDC_CHECK17                     1474
#define IDC_SNR_SHIFT_CHECK             1474
#define IDC_BUTTON_CONNECT              1475
#define IDC_BUTTON_SEND_CMD             1476
#define IDC_BUTTON_READ                 1477
#define IDC_BUTTON_WRITE                1478
#define IDC_BUTTON_TEST_NORMAL          1479

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1476
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
