#ifndef _RDK868_VREGDEF_H_
#define _RDK868_VREGDEF_H_

#define V8_REG_SDIF_BASE						0x000


#define V8_REG_SDIF_STOMODE			(V8_REG_SDIF_BASE+0x0)
#define V8_REG_SDIF_SOFTRESET		(V8_REG_SDIF_BASE+0x1)
#define V8_REG_SDIF_BLKSIZE_H		(V8_REG_SDIF_BASE+0x2)
#define V8_REG_SDIF_BLKSIZE_L		(V8_REG_SDIF_BASE+0x3)
#define V8_REG_SDIF_TRANSBLKCNT_H	(V8_REG_SDIF_BASE+0x4)
#define V8_REG_SDIF_TRANSBLKCNT_L	(V8_REG_SDIF_BASE+0x5)

#define V8_REG_SDIF_CMDARGU_3		(V8_REG_SDIF_BASE+0x6)
#define V8_REG_SDIF_CMDARGU_2		(V8_REG_SDIF_BASE+0x7)
#define V8_REG_SDIF_CMDARGU_1		(V8_REG_SDIF_BASE+0x8)
#define V8_REG_SDIF_CMDARGU_0		(V8_REG_SDIF_BASE+0x9)

#define V8_REG_SDIF_CMDCTRL0		(V8_REG_SDIF_BASE+0xa)
#define V8_REG_SDIF_CMDCTRL1		(V8_REG_SDIF_BASE+0xb)

#define V8_REG_SDIF_RESPREG_15		(V8_REG_SDIF_BASE+0x10)
#define V8_REG_SDIF_RESPREG_14		(V8_REG_SDIF_BASE+0x11)
#define V8_REG_SDIF_RESPREG_13		(V8_REG_SDIF_BASE+0x12)
#define V8_REG_SDIF_RESPREG_12		(V8_REG_SDIF_BASE+0x13)
#define V8_REG_SDIF_RESPREG_11		(V8_REG_SDIF_BASE+0x14)
#define V8_REG_SDIF_RESPREG_10		(V8_REG_SDIF_BASE+0x15)
#define V8_REG_SDIF_RESPREG_09		(V8_REG_SDIF_BASE+0x16)
#define V8_REG_SDIF_RESPREG_08		(V8_REG_SDIF_BASE+0x17)
#define V8_REG_SDIF_RESPREG_07		(V8_REG_SDIF_BASE+0x18)
#define V8_REG_SDIF_RESPREG_06		(V8_REG_SDIF_BASE+0x19)
#define V8_REG_SDIF_RESPREG_05		(V8_REG_SDIF_BASE+0x1A)
#define V8_REG_SDIF_RESPREG_04		(V8_REG_SDIF_BASE+0x1B)
#define V8_REG_SDIF_RESPREG_03		(V8_REG_SDIF_BASE+0x1C)
#define V8_REG_SDIF_RESPREG_02		(V8_REG_SDIF_BASE+0x1D)
#define V8_REG_SDIF_RESPREG_01		(V8_REG_SDIF_BASE+0x1E)
#define V8_REG_SDIF_RESPREG_00		(V8_REG_SDIF_BASE+0x1F)

#define V8_REG_SDIF_DATAPORT_3		(V8_REG_SDIF_BASE+0x20)
#define V8_REG_SDIF_DATAPORT_2		(V8_REG_SDIF_BASE+0x21)
#define V8_REG_SDIF_DATAPORT_1		(V8_REG_SDIF_BASE+0x22)
#define V8_REG_SDIF_DATAPORT_0		(V8_REG_SDIF_BASE+0x23)

#define V8_REG_SDIF_PRESTATE_L		(V8_REG_SDIF_BASE+0x24)
#define V8_REG_SDIF_PRESTATE_H		(V8_REG_SDIF_BASE+0x25)

#define V8_REG_SDIF_DMACTRL			(V8_REG_SDIF_BASE+0x26)
#define V8_REG_SDIF_CLKCTRL			(V8_REG_SDIF_BASE+0x27)

#define V8_REG_SDIF_NORINT_MASK		(V8_REG_SDIF_BASE+0x2c)
#define V8_REG_SDIF_ERR1INT_MASK	(V8_REG_SDIF_BASE+0x2d)
#define V8_REG_SDIF_ERR2INT_MASK	(V8_REG_SDIF_BASE+0x2e)

#define V8_REG_SDIF_NORINT_STATUS	(V8_REG_SDIF_BASE+0x30)
#define V8_REG_SDIF_ERR1INT_STATUS	(V8_REG_SDIF_BASE+0x31)
#define V8_REG_SDIF_ERR2INT_STATUS	(V8_REG_SDIF_BASE+0x32)

#define V8_REG_SDIF_RESP_TMOUTCNT	(V8_REG_SDIF_BASE+0x35)
#define V8_REG_SDIF_BUSYR1B_TMOUT	(V8_REG_SDIF_BASE+0x36)
#define V8_REG_SDIF_BUSYCRC_TMOUT	(V8_REG_SDIF_BASE+0x37)
#define V8_REG_SDIF_WRITECRC_TMOUT	(V8_REG_SDIF_BASE+0x38)
#define V8_REG_SDIF_READ_TMOUT		(V8_REG_SDIF_BASE+0x39)
#define V8_REG_SDIF_CARD_ACTLVL		(V8_REG_SDIF_BASE+0x3A)

#define V8_REG_SDIF_RDMBCMD_INDEX	(V8_REG_SDIF_BASE+0x3C)
#define V8_REG_SDIF_WRSBCMD_INDEX	(V8_REG_SDIF_BASE+0x3D)
#define V8_REG_SDIF_WRMBCMD_INDEX	(V8_REG_SDIF_BASE+0x3E)
#define V8_REG_SDIF_RDSBCMD_INDEX	(V8_REG_SDIF_BASE+0x3F)

#define V8_REG_SDIF_IDRDRESP_DMA3	(V8_REG_SDIF_BASE+0x40)
#define V8_REG_SDIF_IDRDRESP_DMA2	(V8_REG_SDIF_BASE+0x41)
#define V8_REG_SDIF_IDRDRESP_DMA1	(V8_REG_SDIF_BASE+0x42)
#define V8_REG_SDIF_IDRDRESP_DMA0	(V8_REG_SDIF_BASE+0x43)

#define V8_REG_SDIF_IDWRRESP_DMA3	(V8_REG_SDIF_BASE+0x44)
#define V8_REG_SDIF_IDWRRESP_DMA2	(V8_REG_SDIF_BASE+0x45)
#define V8_REG_SDIF_IDWRRESP_DMA1	(V8_REG_SDIF_BASE+0x46)
#define V8_REG_SDIF_IDWRRESP_DMA0	(V8_REG_SDIF_BASE+0x47)

#define V8_REG_SDIF_CRC_THRD		(V8_REG_SDIF_BASE+0x49)

#endif //_VREGDEF_H_


