#ifndef _TRM_MAIN_OPTION_H_
#define _TRM_MAIN_OPTION_H_

#ifndef WIN32

#define V568ANDV938_BOARD	0
#define V568_BOARD			1
#define V938_BOARD			2
#define V568_MAINBOARD		3
#define V938_MAINBOARD		4
#define V578_BOARD			5
#define V578_MAINBOARD		6

#define CURRENT_BOARD	V578_BOARD

#if CURRENT_BOARD == V568ANDV938_BOARD

//#define HOSTCMD_DISABLE
//#define USBCMD_DISABLE
#define DEVICECMD_DISABLE
//#define REGOPER_INWIN32LEVEL

//#define V578CMD_DISABLE
#define V868CMD_DISABLE
//#define V938CMD_DISABLE

#elif CURRENT_BOARD == V568_BOARD

//#define HOSTCMD_DISABLE
#define USBCMD_DISABLE
#define DEVICECMD_DISABLE
//#define REGOPER_INWIN32LEVEL

//#define V578CMD_DISABLE
#define V868CMD_DISABLE
#define V938CMD_DISABLE

//#define V568_CHIPTEST

#elif CURRENT_BOARD == V938_BOARD

//#define HOSTCMD_DISABLE
//#define USBCMD_DISABLE
#define DEVICECMD_DISABLE
//#define REGOPER_INWIN32LEVEL

#define V578CMD_DISABLE
#define V868CMD_DISABLE
//#define V938CMD_DISABLE

#elif CURRENT_BOARD == V568_MAINBOARD

//#define HOSTCMD_DISABLE
//#define USBCMD_DISABLE
#define DEVICECMD_DISABLE
//#define REGOPER_INWIN32LEVEL

//#define V578CMD_DISABLE
#define V868CMD_DISABLE
#define V938CMD_DISABLE

#elif CURRENT_BOARD == V938_MAINBOARD

//#define HOSTCMD_DISABLE
//#define USBCMD_DISABLE
#define DEVICECMD_DISABLE
//#define REGOPER_INWIN32LEVEL

#define V578CMD_DISABLE
#define V868CMD_DISABLE
//#define V938CMD_DISABLE

#elif CURRENT_BOARD == V578_BOARD

//#define HOSTCMD_DISABLE
//#define USBCMD_DISABLE
#define DEVICECMD_DISABLE
//#define REGOPER_INWIN32LEVEL

//#define V578CMD_DISABLE
#define V868CMD_DISABLE
#define V938CMD_DISABLE

//#define V568_CHIPTEST

#elif CURRENT_BOARD == V578_MAINBOARD

//#define HOSTCMD_DISABLE
//#define USBCMD_DISABLE
#define DEVICECMD_DISABLE
//#define REGOPER_INWIN32LEVEL

//#define V578CMD_DISABLE
#define V868CMD_DISABLE
#define V938CMD_DISABLE

#else

#error Please select current demo board!

#endif

#endif

#endif

