//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CmodelPanel.rc
//
#define IDD_CMODEL_DLG                  101
#define IDD_BLK_SENSOR_DLG              102
#define IDD_BLK_SIF_DLG                 103
#define IDD_BLK_ISP_DLG                 104
#define IDD_BLK_IPP_DLG                 105
#define IDD_BLK_LBUF_DLG                106
#define IDD_BLK_JPEG_DLG                107
#define IDD_BLK_MARB_DLG                108
#define IDD_BLK_LCDC_DLG                109
#define IDD_BLK_LCDIF_DLG               110
#define IDD_BLK_GE_DLG                  111
#define IDD_BLK_USBC_DLG                112
#define IDD_BLK_SDIF_DLG                113
#define IDD_BLK_SDCARD_DLG              114
#define IDD_BLK_AUDADC_DLG              115
#define IDD_BLK_BIU_DLG                 116
#define IDD_BLK_CPM_DLG                 117
#define IDD_OLDCMODEL_DLG               118
#define IDD_BLK_TVENC_DLG               119
#define IDC_CHECK_DPD                   1003
#define IDC_CHECK_BLACKLEVEL            1004
#define IDC_CHECK_LENSFALLOFF           1005
#define IDC_CHECK_CFA                   1006
#define IDC_CHECK_DIGITALGAIN           1007
#define IDC_CHECK_COLORCORRECT          1008
#define IDC_CHECK_GAMMACORRECT          1009
#define IDC_CHECK_EDGEENHANCE           1010
#define IDC_BTN_ISP_PROCESS             1011
#define IDC_OPENSRCFILE_BTN             1012
#define IDC_BTN_SEL_ALL                 1012
#define IDC_OPENDESTFILE_BTN            1013
#define IDC_EDIT_BGLINE                 1013
#define IDC_SRCFILE_COMBO               1014
#define IDC_EDIT_GPIXEL                 1014
#define IDC_DESTFILE_COMBO              1015
#define IDC_EDIT_UNIT                   1015
#define IDC_CHECK_RAWDATA               1016
#define IDC_EDIT_LCDC_WIDTH             1016
#define IDC_EDIT1                       1017
#define IDC_EDIT_GAIN                   1017
#define IDC_EDIT_PATTERN_WIDTH          1017
#define IDC_TVINPWIDTH_EDIT             1017
#define IDC_EDIT_DST_WIDTH              1017
#define IDC_LBUFWIDTH_EDIT              1017
#define IDC_EDIT_BLAYER_WIDTH           1017
#define IDC_EDIT_FILE_COUNT             1018
#define IDC_EDIT_IMAGE_WIDTH            1018
#define IDC_TVINPHEIGHT_EDIT            1018
#define IDC_EDIT_DST_HEIGHT             1018
#define IDC_EDIT_LCDC_HEIGHT            1018
#define IDC_BTN_CMODULE_TEST            1019
#define IDC_EDIT_BIT_WISE               1019
#define IDC_EDIT_MEM_WIDTH              1019
#define IDC_EDIT_WIDTH                  1020
#define IDC_EDIT_PATTERN_BG             1020
#define IDC_EDIT_MEM_HEIGHT             1020
#define IDC_EDIT_HEIGHT                 1021
#define IDC_EDIT_PATTERN_FG             1021
#define IDC_EDIT_MEM_POINT_X            1021
#define IDC_BTN_CREATE_RAW_DATA         1022
#define IDC_EDIT_SRC_BG                 1022
#define IDC_EDIT_MEM_POINT_Y            1022
#define IDC_CHECK_JPEG_HEADER           1023
#define IDC_EDIT_SRC_FG                 1023
#define IDC_EDIT_LCD_POINT_X            1023
#define IDC_BTN_COMPARE_Y               1024
#define IDC_EDIT_COLOR_TRANS_SEL        1024
#define IDC_EDIT_LCD_POINT_Y            1024
#define IDC_CHECK_DITHER                1025
#define IDC_EDIT_DST_START              1025
#define IDC_EDIT_AL_WIDTH               1025
#define IDC_STARTCMODEL_BTN             1026
#define IDC_BTN_10TO8                   1026
#define IDC_EDIT_SRC_START              1026
#define IDC_EDIT_MEM_HEIGHT2            1026
#define IDC_EDIT_AL_HEIGHT              1026
#define IDC_CMODELMISC_BTN              1027
#define IDC_EDIT_DPDTHD                 1027
#define IDC_EDIT_SPAN                   1027
#define IDC_EDIT_BLAYER_HEIGHT          1027
#define IDC_PAUSECMODEL_BTN             1028
#define IDC_CHECK_DPDDPC_NEW            1028
#define IDC_EDIT_MEM_WIDTH_B            1028
#define IDC_RUNCMODEL_BUTTON            1029
#define IDC_STOPCMODEL_BTN              1029
#define IDC_BTN_DOCMODULE               1029
#define IDC_CHECK_COLORCONVERT          1029
#define IDC_EDIT_LCD_POINT_X_B          1029
#define IDC_LBUFHEIGHT_EDIT             1030
#define IDC_CBO_SRCFILE2                1030
#define IDC_EDIT_LCD_POINT_Y_B          1030
#define IDC_BTN_OPENFILE                1031
#define IDC_EDIT_MEM_POINT_X_B          1031
#define IDC_AUTOFILE_CHECK              1032
#define IDC_EDIT_PATTERN_HEIGHT         1032
#define IDC_EDIT_MEM_POINT_Y_B          1032
#define IDC_BTN_NEW_CMODULE             1033
#define IDC_EDIT_B_ADDR                 1033
#define IDC_CHECK_OUTPUTFILE            1034
#define IDC_EDIT_IMAGE_HEIGHT           1034
#define IDC_CHECK_BMP                   1035
#define IDC_EDIT_PATTERN_HEIGHT2        1035
#define IDC_EDIT_SHIFT_MAXMOVE          1035
#define IDC_EDIT_TV_DEG                 1036
#define IDC_CHECK1                      1037
#define IDC_CHECK_NEW_EDGE              1037
#define IDC_CHECK_PATTERN_MASK          1037
#define IDC_CHECK_BYPASS                1037
#define IDC_CHECK_702BYPASS             1037
#define IDC_CHECK_ALPHA_BLENDING        1037
#define IDC_EDIT_EDGE00                 1038
#define IDC_CHECK_PATTERN_MASK2         1038
#define IDC_CHECK_SRC_MASK              1038
#define IDC_EDIT_EDGE01                 1039
#define IDC_CHECK_COLOR_TRANS           1039
#define IDC_EDIT_EDGE02                 1040
#define IDC_CHECK_SRC_EXTEND            1040
#define IDC_EDIT_EDGE03                 1041
#define IDC_EDIT_EDGE04                 1042
#define IDC_EDIT_EDGE10                 1043
#define IDC_EDIT_EDGE11                 1044
#define IDC_EDIT_EDGE12                 1045
#define IDC_EDIT_EDGE13                 1046
#define IDC_EDIT_EDGE14                 1047
#define IDC_EDIT_EDGE20                 1048
#define IDC_EDIT_EDGE21                 1049
#define IDC_COLORCONVERT_BUTTON         1050
#define IDC_EDIT_EDGE22                 1050
#define IDC_SRCCLRMATRIX_BUTTON         1051
#define IDC_EDIT_EDGE23                 1051
#define IDC_DSTCLRMATRIX_BUTTON         1052
#define IDC_EDIT_EDGE24                 1052
#define IDC_CONVERT2_BUTTON             1053
#define IDC_EDIT_EDGE30                 1053
#define IDC_GLOBALGAIN_BUTTON           1054
#define IDC_EDIT_EDGE31                 1054
#define IDC_RGB2YUV_BUTTON              1055
#define IDC_EDIT_EDGE32                 1055
#define IDC_YUV2RGB_BUTTON              1056
#define IDC_EDIT_EDGE33                 1056
#define IDC_EDIT_EDGE34                 1057
#define IDC_EDIT_EDGE40                 1058
#define IDC_EDIT_EDGE41                 1059
#define IDC_EDIT_EDGE42                 1060
#define IDC_EDIT_EDGE43                 1061
#define IDC_EDIT_EDGE44                 1062
#define IDC_EDIT3                       1063
#define IDC_EDIT_EDGE_DIV               1063
#define IDC_EDIT_KEY_COLOR              1063
#define IDC_EDIT_EDGE_MAX               1064
#define IDC_CHECK_OUTPUTBMP             1065
#define IDC_EDIT_AH0                    1065
#define IDC_CHECK_AUTOFOCUS             1066
#define IDC_EDIT_EDGE_SUM               1067
#define IDC_EDIT_AH1                    1068
#define IDC_VIDEOFMT_COMBO              1068
#define IDC_LBUFENC_BUTTON              1068
#define IDC_EDIT_AH2                    1069
#define IDC_BUTTON1                     1069
#define IDC_TVCONVERT_BUTTON            1069
#define IDC_BTN_BITBLT                  1069
#define IDC_702JPEGENC_BUTTON           1069
#define IDC_BTN_SIZER                   1069
#define IDC_BTN_PROCESS                 1069
#define IDC_EDIT_AH3                    1070
#define IDC_LPFCONVERT_BUTTON           1070
#define IDC_702JPEGDEC_BUTTON           1070
#define IDC_BTN_BITBLT2                 1070
#define IDC_BTN_INIT_GE                 1070
#define IDC_BUTTON                      1070
#define IDC_LBUFDEC_BUTTON              1070
#define IDC_EDIT_AH4                    1071
#define IDC_702IPPSIZER_BUTTON          1071
#define IDC_EDIT_AV0                    1072
#define IDC_CBO_DST_COLORDEPTH          1072
#define IDC_702IPPRGB_BUTTON            1072
#define IDC_EDIT_AV1                    1073
#define IDC_OUTTYPE_COMBO               1073
#define IDC_CBO_SRC_COLORDEPTH          1073
#define IDC_EDIT_AV2                    1074
#define IDC_CBO_PATTERN_COLORDEPTH      1074
#define IDC_EDIT_AV3                    1075
#define IDC_CBO_START_POINT             1075
#define IDC_702OPCODE_COMBO             1075
#define IDC_702TVOPCODE_COMBO           1075
#define IDC_EDIT_AV4                    1076
#define IDC_702CONVERT_BUTTON           1076
#define IDC_EDIT_WEIGHT00               1077
#define IDC_EDIT_WEIGHT01               1078
#define IDC_EDIT_WEIGHT02               1079
#define IDC_702TVCONVERT_BUTTON         1079
#define IDC_EDIT_WEIGHT03               1080
#define IDC_702IPPCOLOR_COMBO           1080
#define IDC_EDIT_WEIGHT10               1081
#define IDC_EDIT_WEIGHT11               1082
#define IDC_EDIT_WEIGHT12               1083
#define IDC_EDIT_WEIGHT13               1084
#define IDC_EDIT_WEIGHT20               1085
#define IDC_EDIT_WEIGHT21               1086
#define IDC_EDIT_WEIGHT22               1087
#define IDC_EDIT_WEIGHT23               1088
#define IDC_EDIT_WEIGHT30               1089
#define IDC_EDIT_WEIGHT31               1090
#define IDC_EDIT_WEIGHT32               1091
#define IDC_EDIT_EDGE38                 1092
#define IDC_EDIT_WEIGHT33               1092
#define IDC_EDIT_FRAME_NUM              1093
#define IDC_EDIT_H_THRESHOLD            1094
#define IDC_EDIT_MOTION_THRESHOLD       1095
#define IDC_BTN_MOTION                  1096
#define IDC_EDIT4                       1097
#define IDC_EDIT_MOTION_DETECT          1097
#define IDC_EDIT_BLEND_RATIO            1097
#define IDC_QFACTOR_EDIT                1098
#define IDC_CHECK2                      1103
#define IDC_CHECK_702AVERAGE            1103
#define IDC_CHECK_OVERLAY               1103
#define IDC_EDIT_LINE_COLOR             1104
#define IDC_EDIT_START_X                1105
#define IDC_EDIT_START_Y                1106
#define IDC_EDIT_END_X                  1107
#define IDC_EDIT_END_Y                  1108
#define IDC_BTN_LINE_DRAW               1109
#define IDC_EDIT_CLIP_LEFT_X            1110
#define IDC_EDIT_CLIP_LEFT_Y            1111
#define IDC_EDIT_CLIP_RIGHT_X           1112
#define IDC_EDIT_SRC_WIDTH              1112
#define IDC_EDIT_CLIP_RIGHT_Y           1113
#define IDC_EDIT_SRC_HEIGHT             1113
#define IDC_CHECK_RUDEBRC               1113
#define IDC_EDIT_DST_WIDTH2             1114
#define IDC_EDIT_IPP_DST_WIDTH          1114
#define IDC_BRCMODE_COMBO               1114
#define IDC_EDIT_IPP_DST_HEIGHT         1115
#define IDC_CHECK_ONLY_UV               1116
#define IDC_ACNUM_EDIT                  1117
#define IDC_COMBO_ROTATION              1118
#define IDC_COMPON_COMBO                1118
#define IDC_QFCOMP0_EDIT                1119
#define IDC_QFCOMP2_EDIT                1120
#define IDC_QFCOMP1_EDIT                1121
#define IDC_QFCOMP3_EDIT                1122
#define IDC_QFCOMP4_EDIT                1123
#define IDC_QFCOMP5_EDIT                1124
#define IDC__SHIFTL1_EDIT               1125
#define IDC__SHIFTL2_EDIT               1126
#define IDC_RUDETHD_EDIT                1127
#define IDC_LOADCFG_BUTTON              1128
#define IDC__SHIFTR1_EDIT               1129
#define IDC__SHIFTR2_EDIT               1130
#define IDC__THDL1_EDIT                 1131
#define IDC__THDR1_EDIT                 1132
#define IDC__THDL2_EDIT                 1133
#define IDC__THDR2_EDIT                 1134
#define IDC_SAVECFG_BUTTON              1135
#define IDC_TCR_EDIT                    1136
#define IDC_CFGFILE_COMBO               1137
#define IDC_OPENCFGFILE_BUTTON          1138
#define IDC_BUTTON2                     1139
#define IDC_BTN_PROCESS_B               1139
#define IDC_CHECK3                      1139
#define IDC_CHECK_AUTOBRC               1139
#define IDC_COMBO_ROTATION_B            1140
#define IDC_COMBO_ROTATION_B2           1141
#define IDC_COMBO_FORMAT_B              1141
#define IDC_BTN_INIT_GBUF               1143
#define IDC_BTN_LCDC_PROCESS            1144
#define IDC_COMBO_OVERLAY_MODE          1146
#define IDC_COMBO2                      1147
#define IDC_COMBO_LAYER_SELECT          1147
#define IDC_COMBO_LAYER_PRI             1148
#define IDC_BTN_OUTPUT_BMP              1149
#define IDC_BTN_OUTPUT_BMP2             1150
#define IDC_BTN_UPDATE_B                1150
#define IDC_COMBO_SPECIAL_EFFECT        1194
#define IDC_MAT11_EDIT                  1290
#define IDC_MATRIX11_EDIT               1291
#define IDC_MAXCAP_EDIT                 1292
#define IDC_MAT12_EDIT                  1293
#define IDC_MAT13_EDIT                  1294
#define IDC_MAT21_EDIT                  1295
#define IDC_MAT22_EDIT                  1296
#define IDC_MAT23_EDIT                  1297
#define IDC_MAT31_EDIT                  1298
#define IDC_MAT32_EDIT                  1299
#define IDC_MAT33_EDIT                  1300
#define IDC_MATRIX12_EDIT               1301
#define IDC_MATRIX13_EDIT               1302
#define IDC_MATRIX21_EDIT               1303
#define IDC_SCRBAR_U_OFFSET             1303
#define IDC_MATRIX22_EDIT               1304
#define IDC_SCRBAR_V_OFFSET             1304
#define IDC_MATRIX23_EDIT               1305
#define IDC_SCRBAR_U_UP                 1305
#define IDC_MATRIX31_EDIT               1306
#define IDC_SCRBAR_U_DOWN               1306
#define IDC_MATRIX32_EDIT               1307
#define IDC_SCRBAR_V_DOWN               1307
#define IDC_MATRIX33_EDIT               1308
#define IDC_SCRBAR_V_UP                 1308
#define IDC_MINCAP_EDIT                 1309
#define IDC_EDIT_U_OFFSET               1309
#define IDC_EDIT_V_OFFSET               1310
#define IDC_GLOBALGAIN_EDIT             1311
#define IDC_EDIT_U_DOWN                 1311
#define IDC_EDIT_U_UP                   1312
#define IDC_EDIT_V_DOWN                 1313
#define IDC_EDIT_V_UP                   1314

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        112
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1150
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
