//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ToolsPanel.rc
//
#define IDD_TOOLS1_DLG                  250

#define IDD_TOOLS2_DLG                  251
#define IDD_TOOLS3_DLG                  252
#define IDD_TOOLS4_DLG                  253
#define IDD_TOOLS5_DLG                  254
#define IDD_TOOLS6_DLG                  255
#define IDD_TOOLS7_DLG                  256
#define IDD_TOOLS8_DLG                  257
#define IDD_TOOLS9_DLG                  258
#define IDC_UNITCVT_BUTTON              1001
#define IDC_TOOL2MISC_BUTTON            1001
#define IDC_STATIC1                     1002
#define IDC_UNITCVT2_BUTTON2            1002
#define IDC_TOOL3MISC_BUTTON            1003
#define IDC_TOOL3PLAY_BUTTON            1004
#define IDC_BUTTON1                     1004
#define IDC_TOOLS4MISC_BUTTON           1004
#define IDC_IMGSTAT_BUTTON              1004
#define IDC_GAMA                        1004
#define IDC_LEX_ANALYSIS                1004
#define IDC_BTN_VMALLOC                 1004
#define IDC_TOOL3PAUSE_BUTTON           1005
#define IDC_BMPFMT2_EDIT                1005
#define IDC_BTN_VMALLOC2                1005
#define IDC_BTN_VFREE                   1005
#define IDC_TOOL3STOP_BUTTON            1006
#define IDC_BMPWIDTH2_EDIT              1006
#define IDC_TOOL3STOP_BUTTON2           1007
#define IDC_TOOL3PRINT_BUTTON           1007
#define IDC_FRAMERATE_COMBO             1007
#define IDC_STARTFRAME_EDIT             1008
#define IDC_ENDFRAME_EDIT               1009
#define IDC_CONVERT_BUTTON              1011
#define IDC_SPLITJPG2_BUTTON            1011
#define IDC_OPENSRCFILE_BTN             1012
#define IDC_CHKJPGLIST2_BUTTON          1012
#define IDC_OPENDESTFILE_BTN            1013
#define IDC_COPY2_BUTTON                1013
#define IDC_SRCVAL_EDIT                 1013
#define IDC_SRCFILE_COMBO               1014
#define IDC_DSTVAL_EDIT                 1014
#define IDC_DESTFILE_COMBO              1015
#define IDC_WIDTH2_EDIT                 1015
#define IDC_HEX2BIN_BUTTON              1016
#define IDC_HEIGHT2_EDIT                1016
#define IDC_COMPARE_BUTTON              1017
#define IDC_DSTWIDTH2_EDIT              1017
#define IDC_BIN2HEX_BUTTON              1018
#define IDC_DSTHEIGHT2_EDIT             1018
#define IDC_CREATEORDERHEX_BUTTON       1019
#define IDC_FACTOREN2_CHECK             1019
#define IDC_DROPHIGH_BUTTON             1020
#define IDC_HFACTOR2_EDIT               1020
#define IDC_DROPLOW_BUTTON              1021
#define IDC_VFACTOR2_EDIT               1021
#define IDC_PRINTBMPINFO_BUTTON         1022
#define IDC_DATARESIZE2_BUTTON          1022
#define IDC_DESTFORMAT_COMBO            1023
#define IDC_IMGPLAY2_BUTTON             1023
#define IDC_MISCTOOLS_BUTTON            1024
#define IDC_DATASIZER2_BUTTON           1024
#define IDC_BYTEWIDTH_COMBO             1025
#define IDC_POINTY2_EDIT                1025
#define IDC_DIVDATA_COMBO               1026
#define IDC_POINTX2_EDIT                1026
#define IDC_OPENSRCFILE2_BTN            1027
#define IDC_SRCFORMAT2_COMBO            1027
#define IDC_DATACONVERT_BUTTON          1028
#define IDC_OPENSRCFILE2_BTN2           1028
#define IDC_DATARESIZE_BUTTON           1029
#define IDC_DESTFORMAT2_COMBO           1029
#define IDC_WIDTH_EDIT                  1030
#define IDC_BYTEPERDATA2_COMBO          1030
#define IDC_HEIGHT_EDIT                 1031
#define IDC_DATACONVERT2_BUTTON         1031
#define IDC_AUTOFILE_CHECK              1032
#define IDC_COMPAREIMG_BUTTON           1032
#define IDC_DITHER2_CHECK               1032
#define IDC_BYTEPERDATA_COMBO           1033
#define IDC_FILTER02_EDIT               1033
#define IDC_SRCFORMAT_COMBO             1034
#define IDC_FILTER02_EDIT2              1034
#define IDC_MAXVALUE_EDIT               1035
#define IDC_FILTER02_EDIT3              1035
#define IDC_DSTWIDTH_EDIT               1036
#define IDC_FILTER02_EDIT4              1036
#define IDC_DSTHEIGHT_EDIT              1037
#define IDC_PREFILTER2_BUTTON           1037
#define IDC_COPY_BUTTON                 1038
#define IDC_ROTATE2_BUTTON              1038
#define IDC_SRCFILE2_COMBO              1039
#define IDC_ROTATEMODE2_COMBO           1039
#define IDC_DITHER_CHECK                1040
#define IDC_SRCFILE2_COMBO2             1040
#define IDC_BMPWIDTH_EDIT               1041
#define IDC_IMGOPEN2_BUTTON             1041
#define IDC_APPENDFILE_BUTTON           1042
#define IDC_ENDFRAME2_EDIT              1042
#define IDC_BMPHEIGHT_EDIT              1043
#define IDC_STARTFRAME2_EDIT            1043
#define IDC_MERGEFILE_BUTTON            1044
#define IDC_FRAMERATE2_COMBO            1044
#define IDC_DIVDATA_COMBO2              1045
#define IDC_EDIT1                       1045
#define IDC_EDIT_MALLOC_SIZE            1045
#define IDC_MAXYR_EDIT                  1045
#define IDC_AUDT_SAMPLERATE_EDIT        1045
#define IDC_DIVDATA_COMBO3              1046
#define IDC_AUDT_CHANNEL_EDIT           1046
#define IDC_EDIT3                       1046
#define IDC_MINBOX_EDIT                 1047
#define IDC_MINYR_EDIT                  1047
#define IDC_AUDT_SAMPLERATE_EDIT3       1047
#define IDC_AUDT_SAMPLEBITS_EDIT        1047
#define IDC_BMPFMT_EDIT                 1048
#define IDC_SRCBCOUNT_COMBO             1049
#define IDC_AVGYR_EDIT                  1049
#define IDC_DESTBCOUNT_COMBO            1050
#define IDC_MAXUG_EDIT                  1050
#define IDC_OPERATE_COMBO               1051
#define IDC_MINUG_EDIT                  1051
#define IDC_FILTER0_EDIT                1052
#define IDC_AVGUG_EDIT                  1052
#define IDC_FILTER0_EDIT2               1053
#define IDC_MAXVB_EDIT                  1053
#define IDC_FILTER0_EDIT3               1054
#define IDC_MINVB_EDIT                  1054
#define IDC_FILTER0_EDIT4               1055
#define IDC_AVGVB_EDIT                  1055
#define IDC_MAXBOX_EDIT                 1056
#define IDC_EDIT2                       1056
#define IDC_QF_EDIT                     1056
#define IDC_PREFILTER_BUTTON            1057
#define IDC_AUDFINFO_STATIC             1057
#define IDC_HFACTOR_EDIT                1058
#define IDC_BUTTON2                     1058
#define IDC_BTN_WRITE_WAVE              1058
#define IDC_SYN_PARSER                  1058
#define IDC_VFACTOR_EDIT                1059
#define IDC_TOOLS7MISC_BUTTON           1059
#define IDC_FACTOREN_CHECK              1060
#define IDC_TOOLS8MISC_BUTTON           1060
#define IDC_BYTEWIDTH_COMBO2            1061
#define IDC_MISCTOOLS_BUTTON2           1061
#define IDC_SPLITJPG_BUTTON             1061
#define IDC_TOOLS9MISC_BUTTON           1061
#define IDC_POINTX_EDIT                 1062
#define IDC_LIST_MEMMAP                 1062
#define IDC_POINTY_EDIT                 1063
#define IDC_DATASIZER_BUTTON            1064
#define IDC_BUTTON3                     1064
#define IDC_FACTOREN_CHECK2             1065
#define IDC_CHKJPGLIST_BUTTON           1065
#define IDC_HEADFILE_LIST               1065
#define IDC_BIN2ASC_BUTTON              1066
#define IDC_ROTATEMODE_COMBO            1067
#define IDC_ROTATE_BUTTON               1068
#define IDC_COMPAREIMG_BUTTON2          1069
#define IDC_IMGSNR_BUTTON               1069
#define IDC_IMGPLAY_BUTTON              1070
#define IDC_IMGOPEN_BUTTON              1072
#define IDC_ADPCM_FROMAT_COMBO          1072
#define IDC_FORMAT_TYPE_COMBO           1087
#define IDC_CHANNEL_NUMBER_COMBO        1088
#define IDC_SAMPLES_PER_SEC_COMBO       1089
#define IDC_BIT_PER_SAMPLE_COMBO        1090
#define IDC_HRTFBUF_3D_POSITION_COMBO   1091
#define IDC_LOAD_3D_POSITION_BUTTON     1092
#define IDC_MAP_                        1091
#define IDC_MAPSYN_PARSER               1091
#define IDC_MAPLEX                      1092
#define IDC_BMPHEIGHT2_EDIT             1107
#define IDC_PRINTBMPINFO2_BUTTON        1108
#define IDC_COMPAREIMG2_BUTTON          1109
#define IDC_IMGSNR2_BUTTON              1110
#define IDC_SPANCVT_BUTTON              1175
#define IDC_SEQCVT_BUTTON               1176

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1093
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
